import os
from PyQt6.QtWidgets import QMessageBox

PLUGIN_NAME = "ORCA Input Generator Pro"
PLUGIN_VERSION = "2.4.0"
PLUGIN_AUTHOR = "HiroYokoyama"
PLUGIN_DESCRIPTION = "Advanced ORCA Input Generator with Preview and Presets."
SETTINGS_FILE = os.path.join(os.path.dirname(__file__), "settings.json")


def get_default_settings():
    return {
        "nproc": 4,
        "maxcore": 2000,
        "route": "! B3LYP def2-SVP RIJCOSX Def2/J Opt Freq",
        "adv": "",
        "adv_post": "",
        "comment": "Generated by MoleditPy ORCA Input Generator Pro Plugin",
        "coord_format": "Cartesian XYZ",
    }


current_settings = get_default_settings()
_dialog_opened = False  # Guard: don't write to project file until dialog is used


def run(mw):
    if hasattr(mw, "host"):
        mw = mw.host
    from .main_dialog import OrcaSetupDialogPro

    mol = None
    try:
        if hasattr(mw, "view_3d_manager"):
            mol = mw.view_3d_manager.current_mol
        elif hasattr(mw, "current_mol"):
            mol = mw.current_mol
    except Exception:
        mol = None
    if not mol:
        QMessageBox.warning(mw, PLUGIN_NAME, "No molecule loaded.")
        return
    filename = None
    try:
        if hasattr(mw, "init_manager"):
            filename = getattr(mw.init_manager, "current_file_path", None)
    except Exception:
        filename = None
    if not filename and hasattr(mw, "windowTitle"):
        title = mw.windowTitle()
        filename = title.split(" - ")[0].strip() if " - " in title else title.strip()
    if hasattr(mw, "orca_dialog") and mw.orca_dialog and mw.orca_dialog.isVisible():
        mw.orca_dialog.raise_()
        mw.orca_dialog.activateWindow()
        return

    global _dialog_opened
    _dialog_opened = True

    def _mark_modified():
        try:
            mw.state_manager.has_unsaved_changes = True
            mw.state_manager.update_window_title()
        except Exception:
            pass

    # Pass persistent settings to the dialog
    mw.orca_dialog = OrcaSetupDialogPro(
        parent=mw, mol=mol, filename=filename, persistent_settings=current_settings,
        mark_modified=_mark_modified,
    )
    mw.orca_dialog.show()


def initialize(context):
    def show_dialog():
        mw = context.get_main_window()
        run(mw)

    context.add_export_action("ORCA Input...", show_dialog)

    # Register Persistence Handlers
    def on_save():
        # Don't write anything to the project file until the user has
        # actually opened the dialog at least once in this session.
        if not _dialog_opened:
            return None
        return current_settings

    _MOLECULE_KEYS = {"charge", "mult"}

    def on_load(data):
        if isinstance(data, dict) and data:
            # Strip molecule-specific keys that may exist in older project files
            filtered = {k: v for k, v in data.items() if k not in _MOLECULE_KEYS}
            current_settings.update(filtered)
            global _dialog_opened
            _dialog_opened = True

    def on_reset():
        global _dialog_opened
        _dialog_opened = False
        current_settings.clear()
        current_settings.update(get_default_settings())
        # Close and discard the dialog if it is open
        try:
            mw = context.get_main_window()
            dlg = getattr(mw, "orca_dialog", None)
            if dlg is not None:
                dlg.close()
                mw.orca_dialog = None
        except Exception:
            pass

    context.register_save_handler(on_save)
    context.register_load_handler(on_load)
    context.register_document_reset_handler(on_reset)
