import os
from PyQt6.QtWidgets import QMessageBox

PLUGIN_NAME = "ORCA Input Generator Pro"
PLUGIN_VERSION = "3.0.0"
PLUGIN_AUTHOR = "HiroYokoyama"
PLUGIN_DESCRIPTION = "Advanced ORCA Input Generator with Preview and Presets."
PLUGIN_SUPPORTED_MOLEDITPY_VERSION = "4.*"
SETTINGS_FILE = os.path.join(os.path.dirname(__file__), "settings.json")


def get_default_settings():
    return {
        "nproc": 4,
        "maxcore": 2000,
        "route": "! B3LYP def2-SVP RIJCOSX Def2/J Opt Freq",
        "adv": "",
        "adv_post": "",
        "comment": "Generated by MoleditPy ORCA Input Generator Pro Plugin",
        "coord_format": "Cartesian (XYZ)",
    }


current_settings = get_default_settings()
_dialog_opened = False  # Guard: don't write to project file until dialog is used
_context = None  # Stored from initialize() so run() can use the context API


def run(mw):
    global _dialog_opened

    # Prefer the stable context API over direct mw access
    if _context is not None:
        mw = _context.get_main_window()

    from .main_dialog import OrcaSetupDialogPro

    mol = None
    try:
        mol = (
            _context.current_molecule
            if _context is not None
            else getattr(mw, "current_mol", None)
        )
    except Exception:
        mol = None
    if not mol:
        QMessageBox.warning(mw, PLUGIN_NAME, "No molecule loaded.")
        return

    filename = None
    try:
        if hasattr(mw, "init_manager"):
            filename = getattr(mw.init_manager, "current_file_path", None)
    except Exception:
        filename = None
    if not filename and hasattr(mw, "windowTitle"):
        title = mw.windowTitle()
        filename = title.split(" - ")[0].strip() if " - " in title else title.strip()

    if _context is not None:
        dlg = _context.get_window("dialog")
        if dlg is not None and dlg.isVisible():
            dlg.raise_()
            dlg.activateWindow()
            return

    _dialog_opened = True

    def _mark_modified():
        if _context is not None:
            _context.mark_project_modified()

    dlg = OrcaSetupDialogPro(
        parent=mw,
        mol=mol,
        filename=filename,
        persistent_settings=current_settings,
        mark_modified=_mark_modified,
    )
    if _context is not None:
        _context.register_window("dialog", dlg)
    dlg.show()


def initialize(context):
    global _context
    _context = context

    def show_dialog():
        mw = context.get_main_window()
        run(mw)

    context.add_export_action("ORCA Input...", show_dialog)

    # Register Persistence Handlers
    def on_save():
        # Don't write anything to the project file until the user has
        # actually opened the dialog at least once in this session.
        if not _dialog_opened:
            return None
        return current_settings

    _MOLECULE_KEYS = {"charge", "mult"}

    def on_load(data):
        if isinstance(data, dict) and data:
            # Strip molecule-specific keys that may exist in older project files
            filtered = {k: v for k, v in data.items() if k not in _MOLECULE_KEYS}
            current_settings.update(filtered)
            global _dialog_opened
            _dialog_opened = True

    def on_reset():
        global _dialog_opened
        _dialog_opened = False
        current_settings.clear()
        current_settings.update(get_default_settings())
        dlg = context.get_window("dialog")
        if dlg is not None:
            try:
                dlg.close()
            except Exception:
                pass

    context.register_save_handler(on_save)
    context.register_load_handler(on_load)
    context.register_document_reset_handler(on_reset)
