import os
from PyQt6.QtWidgets import QMessageBox

PLUGIN_NAME = "ORCA Input Generator Pro"
PLUGIN_VERSION = "1.0.3"
PLUGIN_AUTHOR = "HiroYokoyama"
PLUGIN_DESCRIPTION = "Advanced ORCA Input Generator with Preview and Presets."
SETTINGS_FILE = os.path.join(os.path.dirname(__file__), "settings.json")

def get_default_settings():
    return {
        "nproc": 4,
        "maxcore": 2000,
        "route": "! B3LYP def2-SVP RIJCOSX Def2/J Opt Freq",
        "adv": "",
        "adv_post": "",
        "comment": "Generated by MoleditPy ORCA Input Generator Pro Plugin",
        "coord_format": "Cartesian XYZ"
    }

current_settings = get_default_settings()

def run(mw):
    from .main_dialog import OrcaSetupDialogPro
    mol = getattr(mw, 'current_mol', None)
    if not mol:
        QMessageBox.warning(mw, PLUGIN_NAME, "No molecule loaded.")
        return
    filename = getattr(mw, 'current_file_path', None)
    if not filename:
         filename = getattr(mw, 'current_file_name', None)
    if not filename and hasattr(mw, 'windowTitle'):
         title = mw.windowTitle()
         filename = title.split(" - ")[0].strip() if " - " in title else title.strip()
    if hasattr(mw, 'orca_dialog') and mw.orca_dialog and mw.orca_dialog.isVisible():
        mw.orca_dialog.raise_()
        mw.orca_dialog.activateWindow()
        return
    
    # Pass persistent settings to the dialog
    mw.orca_dialog = OrcaSetupDialogPro(parent=mw, mol=mol, filename=filename, persistent_settings=current_settings)
    mw.orca_dialog.show()

def initialize(context):
    def show_dialog():
        mw = context.get_main_window()
        run(mw)
    context.add_export_action("ORCA Input...", show_dialog)

    # Register Persistence Handlers
    def on_save():
        return current_settings

    def on_load(data):
        if isinstance(data, dict) and data:
            current_settings.update(data)

    def on_reset():
        current_settings.clear()
        current_settings.update(get_default_settings())

    context.register_save_handler(on_save)
    context.register_load_handler(on_load)
    context.register_document_reset_handler(on_reset)

