# ORCA Methods (Cleaned)
ALL_ORCA_METHODS = [
    # 密度汎関数理論 (DFT)
    "B2GP-PLYP", "B2PLYP", "B3LYP", "B3PW91", "B97-3c", "B97M-rV", "B97M-V", "BHandHLYP", "BLYP", "BP", 
    "BP86", "CAM-B3LYP", "DSD-BLYP", "DSD-PBEP86", "LC-wPBE", "M06", "M06-2X", "M06-HF", "M06-L", 
    "mPW2PLYP", "O3LYP", "PBE", "PBE0", "PBEh-3c", "PTPSS-D3", "PW91", "PWPB95", "r2SCAN-3c", "SCAN", 
    "TPSS", "TPSSh", "wB97", "wB97M-V", "wB97X", "wB97X-D3", "wB97X-V", "wPBE", "wPBEh", "X3LYP",
    # 波動関数理論 (HF / Post-HF)
    "ACPF", "AQCC", "BD", "CASSCF", "CCSD", "CCSD(T)", "CCSD(T)-F12", "CCSD(T)-F12/RI", "CCSD(T)-F12D/RI", 
    "CCSD-F12", "CCSD-F12/RI", "CCSD-F12D/RI", "CEPA/1", "CEPA/2", "CEPA/3", "DLPNO-CCSD", "DLPNO-CCSD(T)", 
    "DLPNO-CCSD(T)-F12", "DLPNO-CCSD(T)-F12/D", "DLPNO-CCSD(T1)", "DLPNO-CCSD(T1)-F12", "DLPNO-CCSD(T1)-F12/D", 
    "DLPNO-CCSD-F12", "DLPNO-CCSD-F12/D", "DLPNO-MP2", "DLPNO-NEVPT2", "DLPNO-SCS-MP2", "DLPNO-SOS-MP2", 
    "F12-DLPNO-MP2", "F12-MP2", "F12-RI-MP2", "F12/D-DLPNO-MP2", "F12/D-RI-MP2", "HF", "MP2", "MP3", "MRCI", 
    "NCEPA/1", "NCPF/1", "NEVPT2", "OO-RI-MP2", "OO-RI-SCS-MP2", "OO-RI-SOS-MP2", "QCISD", "QCISD(T)", 
    "QCISD(T)-F12", "QCISD(T)-F12/RI", "QCISD-F12", "QCISD-F12/RI", "RI-CEPA/1-F12", "RI-MP2", "RI-SCS-MP2", 
    "RI-SOS-MP2", "ROHF", "SCS-MP2", "SCS-MP3", "UHF",
    # 半経験的手法・xTB・力場
    "AM1", "GFN-FF", "GFN0-XTB", "GFN1-XTB", "GFN1-xTB", "GFN2-XTB", "GFN2-xTB", "MNDO", "NATIVE-GFN-XTB", 
    "NATIVE-GFN1-XTB", "NATIVE-GFN2-XTB", "NATIVE-spGFN-XTB", "NATIVE-spGFN1-XTB", "NATIVE-spGFN2-XTB", 
    "NATIVE-spXTB", "NATIVE-spXTB1", "NATIVE-spXTB2", "NATIVE-XTB", "NATIVE-XTB1", "NATIVE-XTB2", "PM3", 
    "PM6", "XTB", "XTB0", "XTB1", "XTB2", "XTBFF", "ZINDO/1", "ZINDO/2", "ZINDO/S", "ZNDDO/1", "ZNDDO/2"
]

# ORCA Basis Sets (Cleaned)
ALL_ORCA_BASIS_SETS = [
    "3-21G", "3-21GSP", "4-22GSP", "6-31++G(2d2p)", "6-31++G(2df2p)", "6-31++G(2df2pd)", "6-31++G(2dp)", 
    "6-31++G(dp)", "6-31++G**", "6-31+G(2d)", "6-31+G(2d2p)", "6-31+G(2df)", "6-31+G(2df2p)", "6-31+G(2df2pd)", 
    "6-31+G(2dp)", "6-31+G(d)", "6-31+G(dp)", "6-31+G*", "6-31+G**", "6-311++G(2d2p)", "6-311++G(2df2p)", 
    "6-311++G(2df2pd)", "6-311++G(2dp)", "6-311++G(3df3pd)", "6-311++G(dp)", "6-311++G**", "6-311+G(2d)", 
    "6-311+G(2d2p)", "6-311+G(2df)", "6-311+G(2df2p)", "6-311+G(2df2pd)", "6-311+G(2dp)", "6-311+G(3df)", 
    "6-311+G(3df2p)", "6-311+G(3df3pd)", "6-311+G(d)", "6-311+G(dp)", "6-311+G*", "6-311+G**", "6-311G", 
    "6-311G(2d)", "6-311G(2d2p)", "6-311G(2df)", "6-311G(2df2p)", "6-311G(2df2pd)", "6-311G(2dp)", "6-311G(3df)", 
    "6-311G(3df3pd)", "6-311G(d)", "6-311G(dp)", "6-311G*", "6-311G**", "6-31G", "6-31G(2d)", "6-31G(2d2p)", 
    "6-31G(2df)", "6-31G(2df2p)", "6-31G(2df2pd)", "6-31G(2dp)", "6-31G(d)", "6-31G(dp)", "6-31G*", "6-31G**", 
    "AHGBS-5", "AHGBS-7", "AHGBS-9", "AHGBSP1-5", "AHGBSP1-7", "AHGBSP1-9", "AHGBSP2-5", "AHGBSP2-7", 
    "AHGBSP2-9", "AHGBSP3-5", "AHGBSP3-7", "AHGBSP3-9", "ANO-pV5Z", "ANO-pV6Z", "ANO-pVDZ", "ANO-pVQZ", 
    "ANO-pVTZ", "ANO-RCC-DZP", "ANO-RCC-Full", "ANO-RCC-QZP", "ANO-RCC-TZP", "ANO-SZ", "apr-cc-pV(Q+d)Z", 
    "aug-ANO-pV5Z", "aug-ANO-pVDZ", "aug-ANO-pVQZ", "aug-ANO-pVTZ", "aug-cc-pCV5Z", "aug-cc-pCV5Z-PP", 
    "aug-cc-pCV6Z", "aug-cc-pCVDZ", "aug-cc-pCVDZ-PP", "aug-cc-pCVQZ", "aug-cc-pCVQZ-PP", "aug-cc-pCVTZ", 
    "aug-cc-pCVTZ-PP", "aug-cc-pV5(+d)Z", "aug-cc-pV5Z", "aug-cc-pV5Z-DK", "aug-cc-pV5Z-PP", "aug-cc-pV6(+d)Z", 
    "aug-cc-pV6Z", "aug-cc-pVD(+d)Z", "aug-cc-pVDZ", "aug-cc-pVDZ-DK", "aug-cc-pVDZ-PP", "aug-cc-pVQ(+d)Z", 
    "aug-cc-pVQZ", "aug-cc-pVQZ-DK", "aug-cc-pVQZ-PP", "aug-cc-pVT(+d)Z", "aug-cc-pVTZ", "aug-cc-pVTZ-DK", 
    "aug-cc-pVTZ-J", "aug-cc-pVTZ-PP", "aug-cc-pwCV5Z", "aug-cc-pwCV5Z-DK", "aug-cc-pwCV5Z-PP", "aug-cc-pwCVDZ", 
    "aug-cc-pwCVDZ-DK", "aug-cc-pwCVDZ-PP", "aug-cc-pwCVQZ", "aug-cc-pwCVQZ-DK", "aug-cc-pwCVQZ-PP", 
    "aug-cc-pwCVTZ", "aug-cc-pwCVTZ-DK", "aug-cc-pwCVTZ-PP", "aug-pc-0", "aug-pc-1", "aug-pc-2", "aug-pc-3", 
    "aug-pc-4", "aug-pcH-1", "aug-pcH-2", "aug-pcH-3", "aug-pcH-4", "aug-pcJ-0", "aug-pcJ-1", "aug-pcJ-2", 
    "aug-pcJ-3", "aug-pcJ-4", "aug-pcseg-0", "aug-pcseg-1", "aug-pcseg-2", "aug-pcseg-3", "aug-pcseg-4", 
    "aug-pcSseg-0", "aug-pcSseg-1", "aug-pcSseg-2", "aug-pcSseg-3", "aug-pcSseg-4", "aug-pcX-1", "aug-pcX-2", 
    "aug-pcX-3", "aug-pcX-4", "cc-pCV5Z", "cc-pCV5Z-PP", "cc-pCV6Z", "cc-pCVDZ", "cc-pCVDZ-F12", "cc-pCVDZ-PP", 
    "cc-pCVQZ", "cc-pCVQZ-F12", "cc-pCVQZ-PP", "cc-pCVTZ", "cc-pCVTZ-F12", "cc-pCVTZ-PP", "cc-pV5(+d)Z", 
    "cc-pV5Z", "cc-pV5Z-DK", "cc-pV5Z-PP", "cc-pV6Z", "cc-pVD(+d)Z", "cc-pVDZ", "cc-pVDZ-DK", "cc-pVDZ-DK3", 
    "cc-pVDZ-F12", "cc-pVDZ-PP", "cc-pVDZ-PP-F12", "cc-pVQ(+d)Z", "cc-pVQZ", "cc-pVQZ-DK", "cc-pVQZ-DK3", 
    "cc-pVQZ-F12", "cc-pVQZ-PP", "cc-pVQZ-PP-F12", "cc-pVT(+d)Z", "cc-pVTZ", "cc-pVTZ-DK", "cc-pVTZ-DK3", 
    "cc-pVTZ-F12", "cc-pVTZ-PP", "cc-pVTZ-PP-F12", "cc-pwCV5Z", "cc-pwCV5Z-DK", "cc-pwCV5Z-PP", "cc-pwCVDZ", 
    "cc-pwCVDZ-DK", "cc-pwCVDZ-DK3", "cc-pwCVDZ-PP", "cc-pwCVQZ", "cc-pwCVQZ-DK", "cc-pwCVQZ-DK3", 
    "cc-pwCVQZ-PP", "cc-pwCVTZ", "cc-pwCVTZ-DK", "cc-pwCVTZ-DK3", "cc-pwCVTZ-PP", "CRENBL", "D95", "D95p", 
    "def-SV(P)", "def-SVP", "def-TZVP", "def-TZVPP", "def2-mSVP", "def2-mTZVP", "def2-mTZVPP", "def2-QZVP", 
    "def2-QZVPD", "def2-QZVPP", "def2-QZVPPD", "def2-SV(P)", "def2-SVP", "def2-SVPD", "def2-TZVP", 
    "def2-TZVP(-f)", "def2-TZVPD", "def2-TZVPP", "def2-TZVPPD", "dhf-QZVP", "dhf-QZVP-2c", "dhf-QZVPP", 
    "dhf-QZVPP-2c", "dhf-SV(P)", "dhf-SVP", "dhf-SVP-2c", "dhf-TZVP", "dhf-TZVP-2c", "dhf-TZVPP", 
    "dhf-TZVPP-2c", "DKH-def2-QZVPP", "DKH-def2-SV(P)", "DKH-def2-SVP", "DKH-def2-TZVP", "DKH-def2-TZVP(-f)", 
    "DKH-def2-TZVPP", "DKH-QZVP", "DKH-QZVPP", "DKH-SV(P)", "DKH-SVP", "DKH-TZV(P)", "DKH-TZVP", "DKH-TZVPP", 
    "EPR-II", "EPR-III", "haV(5+d)Z", "haV(Q+d)Z", "haV(T+d)Z", "HGBS-5", "HGBS-7", "HGBS-9", "HGBSP1-5", 
    "HGBSP1-7", "HGBSP1-9", "HGBSP2-5", "HGBSP2-7", "HGBSP2-9", "HGBSP3-5", "HGBSP3-7", "HGBSP3-9", "IGLO-II", 
    "IGLO-III", "jul-cc-pV(D+d)Z", "jul-cc-pV(Q+d)Z", "jul-cc-pV(T+d)Z", "jun-cc-pV(D+d)Z", "jun-cc-pV(Q+d)Z", 
    "jun-cc-pV(T+d)Z", "LANL08", "LANL08(f)", "LANL2DZ", "LANL2TZ", "LANL2TZ(f)", "m6-31G", "m6-31G*", 
    "ma-def-TZVP", "ma-def2-mSVP", "ma-def2-QZVP", "ma-def2-QZVPP", "ma-def2-SV(P)", "ma-def2-SVP", "ma-def2-TZVP", 
    "ma-def2-TZVP(-f)", "ma-def2-TZVPP", "ma-DKH-def2-QZVPP", "ma-DKH-def2-SV(P)", "ma-DKH-def2-SVP", 
    "ma-DKH-def2-TZVP", "ma-DKH-def2-TZVP(-f)", "ma-DKH-def2-TZVPP", "ma-ZORA-def2-QZVPP", "ma-ZORA-def2-SV(P)", 
    "ma-ZORA-def2-SVP", "ma-ZORA-def2-TZVP", "ma-ZORA-def2-TZVP(-f)", "ma-ZORA-def2-TZVPP", "maug-cc-pV(D+d)Z", 
    "maug-cc-pV(Q+d)Z", "maug-cc-pV(T+d)Z", "may-cc-pV(Q+d)Z", "may-cc-pV(T+d)Z", "MIDI", "MINI", "MINIS", 
    "MINIX", "old-DKH-SV(P)", "old-DKH-SVP", "old-DKH-TZV(P)", "old-DKH-TZVP", "old-DKH-TZVPP", "old-SV", 
    "old-SV(P)", "old-SVP", "old-TZV", "old-TZV(P)", "old-TZVP", "old-TZVPP", "old-ZORA-SV(P)", "old-ZORA-SVP", 
    "old-ZORA-TZV(P)", "old-ZORA-TZVP", "old-ZORA-TZVPP", "Partridge-1", "Partridge-2", "Partridge-3", 
    "Partridge-4", "pc-0", "pc-1", "pc-2", "pc-3", "pc-4", "pcH-1", "pcH-2", "pcH-3", "pcH-4", "pcJ-0", 
    "pcJ-1", "pcJ-2", "pcJ-3", "pcJ-4", "pcseg-0", "pcseg-1", "pcseg-2", "pcseg-3", "pcseg-4", "pcSseg-0", 
    "pcSseg-1", "pcSseg-2", "pcSseg-3", "pcSseg-4", "pcX-1", "pcX-2", "pcX-3", "pcX-4", "QZVP", "QZVPP", 
    "Sapporo-DKH3-DZP-2012", "Sapporo-DKH3-QZP-2012", "Sapporo-DKH3-TZP-2012", "Sapporo-DZP-2012", 
    "Sapporo-QZP-2012", "Sapporo-TZP-2012", "SARC-DKH-SVP", "SARC-DKH-TZVP", "SARC-DKH-TZVPP", "SARC-ZORA-SVP", 
    "SARC-ZORA-TZVP", "SARC-ZORA-TZVPP", "SARC2-DKH-QZV", "SARC2-DKH-QZVP", "SARC2-ZORA-QZV", "SARC2-ZORA-QZVP", 
    "saug-ANO-pV5Z", "saug-ANO-pVDZ", "saug-ANO-pVQZ", "saug-ANO-pVTZ", "STO-3G", "SV", "SV(P)", "SVP", "TZV", 
    "TZV(P)", "TZVP", "TZVPP", "UGBS", "vDZP", "W1-DZ", "W1-mtsmall", "W1-Opt", "W1-QZ", "W1-TZ", "Wachters+f", 
    "x2c-QZVPall", "x2c-QZVPall-2c", "x2c-QZVPall-2c-s", "x2c-QZVPall-s", "x2c-QZVPPall", "x2c-QZVPPall-2c", 
    "x2c-QZVPPall-2c-s", "x2c-QZVPPall-s", "x2c-SV(P)all", "x2c-SV(P)all-2c", "x2c-SV(P)all-s", "x2c-SVPall", 
    "x2c-SVPall-2c", "x2c-SVPall-s", "x2c-TZVPall", "x2c-TZVPall-2c", "x2c-TZVPall-s", "x2c-TZVPPall", 
    "x2c-TZVPPall-2c", "x2c-TZVPPall-s", "ZORA-def2-QZVPP", "ZORA-def2-SV(P)", "ZORA-def2-SVP", "ZORA-def2-TZVP", 
    "ZORA-def2-TZVP(-f)", "ZORA-def2-TZVPP", "ZORA-QZVP", "ZORA-QZVPP", "ZORA-SV(P)", "ZORA-SVP", "ZORA-TZV(P)", 
    "ZORA-TZVP", "ZORA-TZVPP"
]