# ORCA Methods (Cleaned)
ALL_ORCA_METHODS = [
    # 密度汎関数理論 (DFT)
    "B2GP-PLYP",
    "B2PLYP",
    "B3LYP",
    "B3PW91",
    "B97-3c",
    "B97M-rV",
    "B97M-V",
    "BHandHLYP",
    "BLYP",
    "BP",
    "BP86",
    "CAM-B3LYP",
    "DSD-BLYP",
    "DSD-PBEP86",
    "LC-wPBE",
    "M06",
    "M06-2X",
    "M06-HF",
    "M06-L",
    "MN12-L",
    "MN15",
    "mPW2PLYP",
    "O3LYP",
    "OPBE",
    "PBE",
    "PBE0",
    "PBEh-3c",
    "PTPSS-D3",
    "PW91",
    "PWPB95",
    "r2SCAN",
    "r2SCAN-3c",
    "revPBE",
    "revPBE0",
    "SCAN",
    "SSB-D",
    "TPSS",
    "TPSSh",
    "wB97",
    "wB97M-V",
    "wB97X",
    "wB97X-D3",
    "wB97X-D4",
    "wB97X-V",
    "wPBE",
    "wPBEh",
    "X3LYP",
    # 波動関数理論 (HF / Post-HF)
    "ACPF",
    "AQCC",
    "BD",
    "CASSCF",
    "CCSD",
    "CCSD(T)",
    "CCSD(T)-F12",
    "CCSD(T)-F12/RI",
    "CCSD(T)-F12D/RI",
    "CCSD-F12",
    "CCSD-F12/RI",
    "CCSD-F12D/RI",
    "CEPA/1",
    "CEPA/2",
    "CEPA/3",
    "DLPNO-CCSD",
    "DLPNO-CCSD(T)",
    "DLPNO-CCSD(T)-F12",
    "DLPNO-CCSD(T)-F12/D",
    "DLPNO-CCSD(T1)",
    "DLPNO-CCSD(T1)-F12",
    "DLPNO-CCSD(T1)-F12/D",
    "DLPNO-CCSD-F12",
    "DLPNO-CCSD-F12/D",
    "DLPNO-EOM-CCSD",
    "EA-EOM-CCSD",
    "EOM-CCSD",
    "IP-EOM-CCSD",
    "SF-EOM-CCSD",
    "STEOM-CCSD",
    "STEOM-DLPNO-CCSD",
    "DLPNO-MP2",
    "DLPNO-NEVPT2",
    "DLPNO-SCS-MP2",
    "DLPNO-SOS-MP2",
    "F12-DLPNO-MP2",
    "F12-MP2",
    "F12-RI-MP2",
    "F12/D-DLPNO-MP2",
    "F12/D-RI-MP2",
    "HF",
    "MP2",
    "MP3",
    "MRCI",
    "NCEPA/1",
    "NCPF/1",
    "NEVPT2",
    "OO-RI-MP2",
    "OO-RI-SCS-MP2",
    "OO-RI-SOS-MP2",
    "QCISD",
    "QCISD(T)",
    "QCISD(T)-F12",
    "QCISD(T)-F12/RI",
    "QCISD-F12",
    "QCISD-F12/RI",
    "RI-CEPA/1-F12",
    "RI-MP2",
    "ROCIS",
    "RI-SCS-MP2",
    "RI-SOS-MP2",
    "ROHF",
    "SCS-MP2",
    "SCS-MP3",
    "UHF",
    # 半経験的手法・xTB・力場
    "AM1",
    "GFN-FF",
    "GFN0-XTB",
    "GFN1-XTB",
    "GFN1-xTB",
    "GFN2-XTB",
    "GFN2-xTB",
    "MNDO",
    "NATIVE-GFN-XTB",
    "NATIVE-GFN1-XTB",
    "NATIVE-GFN2-XTB",
    "NATIVE-spGFN-XTB",
    "NATIVE-spGFN1-XTB",
    "NATIVE-spGFN2-XTB",
    "NATIVE-spXTB",
    "NATIVE-spXTB1",
    "NATIVE-spXTB2",
    "NATIVE-XTB",
    "NATIVE-XTB1",
    "NATIVE-XTB2",
    "PM3",
    "PM6",
    "XTB",
    "XTB0",
    "XTB1",
    "XTB2",
    "XTBFF",
    "ZINDO/1",
    "ZINDO/2",
    "ZINDO/S",
    "ZNDDO/1",
    "ZNDDO/2",
]

# ORCA Basis Sets (Cleaned)
ALL_ORCA_BASIS_SETS = [
    "3-21G",
    "3-21GSP",
    "4-22GSP",
    "6-31++G(2d2p)",
    "6-31++G(2df2p)",
    "6-31++G(2df2pd)",
    "6-31++G(2dp)",
    "6-31++G(dp)",
    "6-31++G**",
    "6-31+G(2d)",
    "6-31+G(2d2p)",
    "6-31+G(2df)",
    "6-31+G(2df2p)",
    "6-31+G(2df2pd)",
    "6-31+G(2dp)",
    "6-31+G(d)",
    "6-31+G(dp)",
    "6-31+G*",
    "6-31+G**",
    "6-311++G(2d2p)",
    "6-311++G(2df2p)",
    "6-311++G(2df2pd)",
    "6-311++G(2dp)",
    "6-311++G(3df3pd)",
    "6-311++G(dp)",
    "6-311++G**",
    "6-311+G(2d)",
    "6-311+G(2d2p)",
    "6-311+G(2df)",
    "6-311+G(2df2p)",
    "6-311+G(2df2pd)",
    "6-311+G(2dp)",
    "6-311+G(3df)",
    "6-311+G(3df2p)",
    "6-311+G(3df3pd)",
    "6-311+G(d)",
    "6-311+G(dp)",
    "6-311+G*",
    "6-311+G**",
    "6-311G",
    "6-311G(2d)",
    "6-311G(2d2p)",
    "6-311G(2df)",
    "6-311G(2df2p)",
    "6-311G(2df2pd)",
    "6-311G(2dp)",
    "6-311G(3df)",
    "6-311G(3df3pd)",
    "6-311G(d)",
    "6-311G(dp)",
    "6-311G*",
    "6-311G**",
    "6-31G",
    "6-31G(2d)",
    "6-31G(2d2p)",
    "6-31G(2df)",
    "6-31G(2df2p)",
    "6-31G(2df2pd)",
    "6-31G(2dp)",
    "6-31G(d)",
    "6-31G(dp)",
    "6-31G*",
    "6-31G**",
    "AHGBS-5",
    "AHGBS-7",
    "AHGBS-9",
    "AHGBSP1-5",
    "AHGBSP1-7",
    "AHGBSP1-9",
    "AHGBSP2-5",
    "AHGBSP2-7",
    "AHGBSP2-9",
    "AHGBSP3-5",
    "AHGBSP3-7",
    "AHGBSP3-9",
    "ANO-pV5Z",
    "ANO-pV6Z",
    "ANO-pVDZ",
    "ANO-pVQZ",
    "ANO-pVTZ",
    "ANO-RCC-DZP",
    "ANO-RCC-Full",
    "ANO-RCC-QZP",
    "ANO-RCC-TZP",
    "ANO-SZ",
    "apr-cc-pV(Q+d)Z",
    "aug-ANO-pV5Z",
    "aug-ANO-pVDZ",
    "aug-ANO-pVQZ",
    "aug-ANO-pVTZ",
    "aug-cc-pCV5Z",
    "aug-cc-pCV5Z-PP",
    "aug-cc-pCV6Z",
    "aug-cc-pCVDZ",
    "aug-cc-pCVDZ-PP",
    "aug-cc-pCVQZ",
    "aug-cc-pCVQZ-PP",
    "aug-cc-pCVTZ",
    "aug-cc-pCVTZ-PP",
    "aug-cc-pV5(+d)Z",
    "aug-cc-pV5Z",
    "aug-cc-pV5Z-DK",
    "aug-cc-pV5Z-PP",
    "aug-cc-pV6(+d)Z",
    "aug-cc-pV6Z",
    "aug-cc-pVD(+d)Z",
    "aug-cc-pVDZ",
    "aug-cc-pVDZ-DK",
    "aug-cc-pVDZ-PP",
    "aug-cc-pVQ(+d)Z",
    "aug-cc-pVQZ",
    "aug-cc-pVQZ-DK",
    "aug-cc-pVQZ-PP",
    "aug-cc-pVT(+d)Z",
    "aug-cc-pVTZ",
    "aug-cc-pVTZ-DK",
    "aug-cc-pVTZ-J",
    "aug-cc-pVTZ-PP",
    "aug-cc-pwCV5Z",
    "aug-cc-pwCV5Z-DK",
    "aug-cc-pwCV5Z-PP",
    "aug-cc-pwCVDZ",
    "aug-cc-pwCVDZ-DK",
    "aug-cc-pwCVDZ-PP",
    "aug-cc-pwCVQZ",
    "aug-cc-pwCVQZ-DK",
    "aug-cc-pwCVQZ-PP",
    "aug-cc-pwCVTZ",
    "aug-cc-pwCVTZ-DK",
    "aug-cc-pwCVTZ-PP",
    "aug-pc-0",
    "aug-pc-1",
    "aug-pc-2",
    "aug-pc-3",
    "aug-pc-4",
    "aug-pcH-1",
    "aug-pcH-2",
    "aug-pcH-3",
    "aug-pcH-4",
    "aug-pcJ-0",
    "aug-pcJ-1",
    "aug-pcJ-2",
    "aug-pcJ-3",
    "aug-pcJ-4",
    "aug-pcseg-0",
    "aug-pcseg-1",
    "aug-pcseg-2",
    "aug-pcseg-3",
    "aug-pcseg-4",
    "aug-pcSseg-0",
    "aug-pcSseg-1",
    "aug-pcSseg-2",
    "aug-pcSseg-3",
    "aug-pcSseg-4",
    "aug-pcX-1",
    "aug-pcX-2",
    "aug-pcX-3",
    "aug-pcX-4",
    "cc-pCV5Z",
    "cc-pCV5Z-PP",
    "cc-pCV6Z",
    "cc-pCVDZ",
    "cc-pCVDZ-F12",
    "cc-pCVDZ-PP",
    "cc-pCVQZ",
    "cc-pCVQZ-F12",
    "cc-pCVQZ-PP",
    "cc-pCVTZ",
    "cc-pCVTZ-F12",
    "cc-pCVTZ-PP",
    "cc-pV5(+d)Z",
    "cc-pV5Z",
    "cc-pV5Z-DK",
    "cc-pV5Z-PP",
    "cc-pV6Z",
    "cc-pVD(+d)Z",
    "cc-pVDZ",
    "cc-pVDZ-DK",
    "cc-pVDZ-DK3",
    "cc-pVDZ-F12",
    "cc-pVDZ-PP",
    "cc-pVDZ-PP-F12",
    "cc-pVQ(+d)Z",
    "cc-pVQZ",
    "cc-pVQZ-DK",
    "cc-pVQZ-DK3",
    "cc-pVQZ-F12",
    "cc-pVQZ-PP",
    "cc-pVQZ-PP-F12",
    "cc-pVT(+d)Z",
    "cc-pVTZ",
    "cc-pVTZ-DK",
    "cc-pVTZ-DK3",
    "cc-pVTZ-F12",
    "cc-pVTZ-PP",
    "cc-pVTZ-PP-F12",
    "cc-pwCV5Z",
    "cc-pwCV5Z-DK",
    "cc-pwCV5Z-PP",
    "cc-pwCVDZ",
    "cc-pwCVDZ-DK",
    "cc-pwCVDZ-DK3",
    "cc-pwCVDZ-PP",
    "cc-pwCVQZ",
    "cc-pwCVQZ-DK",
    "cc-pwCVQZ-DK3",
    "cc-pwCVQZ-PP",
    "cc-pwCVTZ",
    "cc-pwCVTZ-DK",
    "cc-pwCVTZ-DK3",
    "cc-pwCVTZ-PP",
    "CRENBL",
    "D95",
    "D95p",
    "def-SV(P)",
    "def-SVP",
    "def-TZVP",
    "def-TZVPP",
    "def2-mSVP",
    "def2-mTZVP",
    "def2-mTZVPP",
    "def2-QZVP",
    "def2-QZVPD",
    "def2-QZVPP",
    "def2-QZVPPD",
    "def2-SV(P)",
    "def2-SVP",
    "def2-SVPD",
    "def2-TZVP",
    "def2-TZVP(-f)",
    "def2-TZVPD",
    "def2-TZVPP",
    "def2-TZVPPD",
    "dhf-QZVP",
    "dhf-QZVP-2c",
    "dhf-QZVPP",
    "dhf-QZVPP-2c",
    "dhf-SV(P)",
    "dhf-SVP",
    "dhf-SVP-2c",
    "dhf-TZVP",
    "dhf-TZVP-2c",
    "dhf-TZVPP",
    "dhf-TZVPP-2c",
    "DKH-def2-QZVPP",
    "DKH-def2-SV(P)",
    "DKH-def2-SVP",
    "DKH-def2-TZVP",
    "DKH-def2-TZVP(-f)",
    "DKH-def2-TZVPP",
    "DKH-QZVP",
    "DKH-QZVPP",
    "DKH-SV(P)",
    "DKH-SVP",
    "DKH-TZV(P)",
    "DKH-TZVP",
    "DKH-TZVPP",
    "EPR-II",
    "EPR-III",
    "haV(5+d)Z",
    "haV(Q+d)Z",
    "haV(T+d)Z",
    "HGBS-5",
    "HGBS-7",
    "HGBS-9",
    "HGBSP1-5",
    "HGBSP1-7",
    "HGBSP1-9",
    "HGBSP2-5",
    "HGBSP2-7",
    "HGBSP2-9",
    "HGBSP3-5",
    "HGBSP3-7",
    "HGBSP3-9",
    "IGLO-II",
    "IGLO-III",
    "jul-cc-pV(D+d)Z",
    "jul-cc-pV(Q+d)Z",
    "jul-cc-pV(T+d)Z",
    "jun-cc-pV(D+d)Z",
    "jun-cc-pV(Q+d)Z",
    "jun-cc-pV(T+d)Z",
    "LANL08",
    "LANL08(f)",
    "LANL2DZ",
    "LANL2TZ",
    "LANL2TZ(f)",
    "m6-31G",
    "m6-31G*",
    "ma-def-TZVP",
    "ma-def2-mSVP",
    "ma-def2-QZVP",
    "ma-def2-QZVPP",
    "ma-def2-SV(P)",
    "ma-def2-SVP",
    "ma-def2-TZVP",
    "ma-def2-TZVP(-f)",
    "ma-def2-TZVPP",
    "ma-DKH-def2-QZVPP",
    "ma-DKH-def2-SV(P)",
    "ma-DKH-def2-SVP",
    "ma-DKH-def2-TZVP",
    "ma-DKH-def2-TZVP(-f)",
    "ma-DKH-def2-TZVPP",
    "ma-ZORA-def2-QZVPP",
    "ma-ZORA-def2-SV(P)",
    "ma-ZORA-def2-SVP",
    "ma-ZORA-def2-TZVP",
    "ma-ZORA-def2-TZVP(-f)",
    "ma-ZORA-def2-TZVPP",
    "maug-cc-pV(D+d)Z",
    "maug-cc-pV(Q+d)Z",
    "maug-cc-pV(T+d)Z",
    "may-cc-pV(Q+d)Z",
    "may-cc-pV(T+d)Z",
    "MIDI",
    "MINI",
    "MINIS",
    "MINIX",
    "old-DKH-SV(P)",
    "old-DKH-SVP",
    "old-DKH-TZV(P)",
    "old-DKH-TZVP",
    "old-DKH-TZVPP",
    "old-SV",
    "old-SV(P)",
    "old-SVP",
    "old-TZV",
    "old-TZV(P)",
    "old-TZVP",
    "old-TZVPP",
    "old-ZORA-SV(P)",
    "old-ZORA-SVP",
    "old-ZORA-TZV(P)",
    "old-ZORA-TZVP",
    "old-ZORA-TZVPP",
    "Partridge-1",
    "Partridge-2",
    "Partridge-3",
    "Partridge-4",
    "pc-0",
    "pc-1",
    "pc-2",
    "pc-3",
    "pc-4",
    "pcH-1",
    "pcH-2",
    "pcH-3",
    "pcH-4",
    "pcJ-0",
    "pcJ-1",
    "pcJ-2",
    "pcJ-3",
    "pcJ-4",
    "pcseg-0",
    "pcseg-1",
    "pcseg-2",
    "pcseg-3",
    "pcseg-4",
    "pcSseg-0",
    "pcSseg-1",
    "pcSseg-2",
    "pcSseg-3",
    "pcSseg-4",
    "pcX-1",
    "pcX-2",
    "pcX-3",
    "pcX-4",
    "QZVP",
    "QZVPP",
    "Sapporo-DKH3-DZP-2012",
    "Sapporo-DKH3-QZP-2012",
    "Sapporo-DKH3-TZP-2012",
    "Sapporo-DZP-2012",
    "Sapporo-QZP-2012",
    "Sapporo-TZP-2012",
    "SARC-DKH-SVP",
    "SARC-DKH-TZVP",
    "SARC-DKH-TZVPP",
    "SARC-ZORA-SVP",
    "SARC-ZORA-TZVP",
    "SARC-ZORA-TZVPP",
    "SARC2-DKH-QZV",
    "SARC2-DKH-QZVP",
    "SARC2-ZORA-QZV",
    "SARC2-ZORA-QZVP",
    "saug-ANO-pV5Z",
    "saug-ANO-pVDZ",
    "saug-ANO-pVQZ",
    "saug-ANO-pVTZ",
    "STO-3G",
    "SV",
    "SV(P)",
    "SVP",
    "TZV",
    "TZV(P)",
    "TZVP",
    "TZVPP",
    "UGBS",
    "vDZP",
    "W1-DZ",
    "W1-mtsmall",
    "W1-Opt",
    "W1-QZ",
    "W1-TZ",
    "Wachters+f",
    "x2c-QZVPall",
    "x2c-QZVPall-2c",
    "x2c-QZVPall-2c-s",
    "x2c-QZVPall-s",
    "x2c-QZVPPall",
    "x2c-QZVPPall-2c",
    "x2c-QZVPPall-2c-s",
    "x2c-QZVPPall-s",
    "x2c-SV(P)all",
    "x2c-SV(P)all-2c",
    "x2c-SV(P)all-s",
    "x2c-SVPall",
    "x2c-SVPall-2c",
    "x2c-SVPall-s",
    "x2c-TZVPall",
    "x2c-TZVPall-2c",
    "x2c-TZVPall-s",
    "x2c-TZVPPall",
    "x2c-TZVPPall-2c",
    "x2c-TZVPPall-s",
    "ZORA-def2-QZVPP",
    "ZORA-def2-SV(P)",
    "ZORA-def2-SVP",
    "ZORA-def2-TZVP",
    "ZORA-def2-TZVP(-f)",
    "ZORA-def2-TZVPP",
    "ZORA-QZVP",
    "ZORA-QZVPP",
    "ZORA-SV(P)",
    "ZORA-SVP",
    "ZORA-TZV(P)",
    "ZORA-TZVP",
    "ZORA-TZVPP",
]

ORCA_SEARCH_CATALOG = [
    # --- Job Types & Tasks ---
    ("Job Types", "Opt", "Geometry Optimization to local ground-state minimum"),
    ("Job Types", "OptH", "Optimize Hydrogens only (keeps heavy atoms constrained)"),
    ("Job Types", "Freq", "Harmonic Vibrational Frequency Calculation & Thermochemistry"),
    ("Job Types", "Opt Freq", "Geometry Optimization followed by Frequency Calculation"),
    ("Job Types", "NumFreq", "Numerical (finite difference) Frequency Calculation"),
    ("Job Types", "SP", "Single-Point Energy Calculation"),
    ("Job Types", "OptTS", "Transition State Optimization"),
    ("Job Types", "Scan", "Relaxed Potential Energy Surface Scan (%geom Scan block)"),
    ("Job Types", "IRC", "Intrinsic Reaction Coordinate path integration"),
    ("Job Types", "NEB", "Nudged Elastic Band reaction pathway search"),
    ("Job Types", "NEB-CI", "Climbing-Image Nudged Elastic Band for exact TS location"),
    ("Job Types", "NEB-TS", "NEB followed automatically by TS optimization"),
    ("Job Types", "FAST-NEB-TS", "Fast NEB pre-optimization followed by TS optimization"),
    ("Job Types", "LOOSE-NEB-TS", "Loose NEB path search with TS refinement"),
    ("Job Types", "TIGHT-NEB-TS", "Tight convergence NEB-TS search"),
    ("Job Types", "ZOOM-NEB", "Zooming NEB around highest energy image"),
    ("Job Types", "NEB-IDPP", "NEB with Image-Dependent Pair Potential initial interpolation"),
    ("Job Types", "MD", "Born-Oppenheimer Molecular Dynamics (BOMD) simulation"),
    ("Job Types", "GOAT", "Global Optimization Algorithm for Transitions and Conformers"),
    ("Job Types", "Gradient", "Analytical Energy Gradient calculation"),
    ("Job Types", "Hessian", "Analytical Energy Hessian matrix calculation"),
    ("Job Types", "EnGrad", "Single Point Energy + Analytical Gradient"),
    ("Job Types", "NumGrad", "Numerical Gradient Calculation"),
    ("Job Types", "NumHess", "Numerical Hessian Calculation"),
    ("Job Types", "ESD(ABS)", "Excited State Dynamics vibronic absorption spectrum"),
    ("Job Types", "ESD(FLUOR)", "Excited State Dynamics vibronic fluorescence spectrum"),
    ("Job Types", "NMR", "NMR chemical shielding and spin-spin couplings"),
    ("Job Types", "TightOpt", "Tight geometry optimization convergence criteria"),
    ("Job Types", "VeryTightOpt", "Very tight geometry optimization criteria"),
    ("Job Types", "LooseOpt", "Loose geometry optimization convergence criteria"),
    ("Job Types", "COpt", "Cartesian geometry optimization (avoids internal coords)"),
    ("Job Types", "CalcFC", "Calculate force constants at the first optimization step"),
    ("Job Types", "CalcHess", "Calculate exact Hessian at first step (recommended for TS)"),
    ("Job Types", "MaxIter 256", "Set maximum geometry optimization iterations to 256"),
    ("Job Types", "Raman", "Compute Raman vibrational intensities with numerical polarizabilities"),

    # --- Methods / Functionals ---
    ("Methods / Functionals", "B3LYP", "Becke 3-parameter hybrid GGA (20% HF exchange)"),
    ("Methods / Functionals", "PBE0", "Perdew-Burke-Ernzerhof hybrid functional (25% HF exchange)"),
    ("Methods / Functionals", "wB97X-D3", "Head-Gordon range-separated hybrid with D3 dispersion"),
    ("Methods / Functionals", "wB97M-V", "High-accuracy range-separated meta-GGA with VV10"),
    ("Methods / Functionals", "wB97X-D4", "Range-separated hybrid functional with D4 dispersion"),
    ("Methods / Functionals", "wB97X-V", "Range-separated hybrid with VV10 non-local dispersion"),
    ("Methods / Functionals", "r2SCAN-3c", "Fast composite meta-GGA with mTZVP tailored basis"),
    ("Methods / Functionals", "B97-3c", "Fast composite method for large systems with mSVP basis"),
    ("Methods / Functionals", "PBEh-3c", "Fast composite hybrid functional with modified def2-SVP"),
    ("Methods / Functionals", "r2SCAN", "Modern accurate meta-GGA functional"),
    ("Methods / Functionals", "SCAN", "Strongly constrained and appropriately normed meta-GGA"),
    ("Methods / Functionals", "M06-2X", "Truhlar high-nonlocality hybrid meta-GGA (54% HF exchange)"),
    ("Methods / Functionals", "M06", "Minnesota hybrid meta-GGA for transition metal chemistry"),
    ("Methods / Functionals", "M06-L", "Minnesota local pure meta-GGA functional"),
    ("Methods / Functionals", "M06-HF", "Minnesota hybrid functional with 100% HF exchange"),
    ("Methods / Functionals", "CAM-B3LYP", "Handy range-separated hybrid for charge-transfer & TD-DFT"),
    ("Methods / Functionals", "LC-wPBE", "Long-range corrected PBE functional"),
    ("Methods / Functionals", "B2PLYP", "Grimme double-hybrid functional (with MP2 correlation)"),
    ("Methods / Functionals", "B2GP-PLYP", "General purpose double-hybrid functional"),
    ("Methods / Functionals", "DSD-BLYP", "Dispersion-corrected spin-component-scaled double hybrid"),
    ("Methods / Functionals", "DSD-PBEP86", "Dispersion-corrected spin-component-scaled double hybrid"),
    ("Methods / Functionals", "mPW2PLYP", "Modified PW91 exchange double-hybrid functional"),
    ("Methods / Functionals", "PWPB95", "Perdew-Wang modified double hybrid functional"),
    ("Methods / Functionals", "DLPNO-CCSD(T)", "Domain-based local pair natural orbital CCSD(T)"),
    ("Methods / Functionals", "DLPNO-CCSD", "Domain-based local pair natural orbital CCSD"),
    ("Methods / Functionals", "DLPNO-MP2", "Domain-based local pair natural orbital MP2"),
    ("Methods / Functionals", "MP2", "Second-order Møller-Plesset perturbation theory"),
    ("Methods / Functionals", "RI-MP2", "Resolution-of-identity accelerated MP2"),
    ("Methods / Functionals", "HF", "Hartree-Fock self-consistent field"),
    ("Methods / Functionals", "UHF", "Unrestricted Hartree-Fock for open-shell systems"),
    ("Methods / Functionals", "ROHF", "Restricted Open-Shell Hartree-Fock"),
    ("Methods / Functionals", "PBE", "Perdew-Burke-Ernzerhof non-empirical GGA functional"),
    ("Methods / Functionals", "BP86", "Becke 88 exchange with Perdew 86 correlation"),
    ("Methods / Functionals", "BLYP", "Becke-Lee-Yang-Parr pure GGA functional"),
    ("Methods / Functionals", "TPSS", "Tao-Perdew-Staroverov-Scuseria meta-GGA functional"),
    ("Methods / Functionals", "TPSSh", "Hybrid meta-GGA functional (10% HF exchange)"),
    ("Methods / Functionals", "B3PW91", "Becke 3-parameter hybrid with PW91 correlation"),
    ("Methods / Functionals", "CASSCF", "Complete active space multiconfigurational SCF"),
    ("Methods / Functionals", "NEVPT2", "N-electron valence perturbation theory for CASSCF"),
    ("Methods / Functionals", "MRCI", "Multireference Configuration Interaction"),
    ("Methods / Functionals", "CCSD", "Coupled Cluster Singles and Doubles"),
    ("Methods / Functionals", "CCSD(T)", "Coupled Cluster with Singles, Doubles and perturbative Triples"),

    # --- Basis Sets ---
    ("Basis Sets", "def2-SVP", "Karlsruhe split-valence polarized basis set"),
    ("Basis Sets", "def2-TZVP", "Karlsruhe triple-zeta valence polarized basis set"),
    ("Basis Sets", "def2-TZVPP", "Karlsruhe triple-zeta valence double-polarized basis set"),
    ("Basis Sets", "def2-QZVP", "Karlsruhe quadruple-zeta valence polarized basis set"),
    ("Basis Sets", "def2-QZVPP", "Karlsruhe quadruple-zeta valence double-polarized basis set"),
    ("Basis Sets", "ma-def2-SVP", "Minimally augmented def2-SVP for anions/Rydberg states"),
    ("Basis Sets", "ma-def2-TZVP", "Minimally augmented def2-TZVP for anions/polarizabilities"),
    ("Basis Sets", "ma-def2-QZVP", "Minimally augmented def2-QZVP for high-precision properties"),
    ("Basis Sets", "cc-pVDZ", "Dunning correlation-consistent double-zeta basis set"),
    ("Basis Sets", "cc-pVTZ", "Dunning correlation-consistent triple-zeta basis set"),
    ("Basis Sets", "cc-pVQZ", "Dunning correlation-consistent quadruple-zeta basis set"),
    ("Basis Sets", "aug-cc-pVDZ", "Augmented Dunning correlation-consistent double-zeta basis"),
    ("Basis Sets", "aug-cc-pVTZ", "Augmented Dunning correlation-consistent triple-zeta basis"),
    ("Basis Sets", "aug-cc-pVQZ", "Augmented Dunning correlation-consistent quadruple-zeta basis"),
    ("Basis Sets", "6-31G", "Pople split-valence double-zeta basis set"),
    ("Basis Sets", "6-31G*", "Pople double-zeta polarized basis set (same as 6-31G(d))"),
    ("Basis Sets", "6-311G*", "Pople triple-zeta polarized basis set (6-311G(d))"),
    ("Basis Sets", "6-311+G*", "Pople triple-zeta with diffuse and polarization on heavy atoms"),
    ("Basis Sets", "6-311++G**", "Pople triple-zeta with diffuse and polarization on all atoms"),
    ("Basis Sets", "pc-1", "Jensen polarization-consistent double-zeta basis set for DFT"),
    ("Basis Sets", "pc-2", "Jensen polarization-consistent triple-zeta basis set for DFT"),
    ("Basis Sets", "aug-pc-1", "Augmented Jensen polarization-consistent double-zeta basis"),
    ("Basis Sets", "aug-pc-2", "Augmented Jensen polarization-consistent triple-zeta basis"),
    ("Basis Sets", "EPR-II", "Barone basis set optimized for EPR hyperfine couplings"),
    ("Basis Sets", "EPR-III", "Barone triple-zeta basis set for EPR hyperfine couplings"),
    ("Basis Sets", "IGLO-II", "Kutzelnigg basis set for NMR shielding calculations"),
    ("Basis Sets", "IGLO-III", "Kutzelnigg triple-zeta basis set for NMR shieldings"),
    ("Basis Sets", "def2/J", "Coulomb fitting auxiliary basis set for def2 family"),
    ("Basis Sets", "def2/JK", "Coulomb and exchange fitting auxiliary basis set"),
    ("Basis Sets", "def2-TZVP/C", "Correlation fitting auxiliary basis set for def2-TZVP"),
    ("Basis Sets", "AutoAux", "Automatically generated auxiliary basis set"),
    ("Basis Sets", "NoAux", "Disable auxiliary basis set fitting"),

    # --- Solvation ---
    ("Solvation", "CPCM(Water)", "CPCM implicit solvent model for water (epsilon=80.4)"),
    ("Solvation", "CPCM(Acetonitrile)", "CPCM implicit solvent model for acetonitrile (epsilon=37.5)"),
    ("Solvation", "CPCM(Methanol)", "CPCM implicit solvent model for methanol (epsilon=32.6)"),
    ("Solvation", "CPCM(Ethanol)", "CPCM implicit solvent model for ethanol (epsilon=24.3)"),
    ("Solvation", "CPCM(Chloroform)", "CPCM implicit solvent model for chloroform (epsilon=4.8)"),
    ("Solvation", "CPCM(Dichloromethane)", "CPCM implicit solvent model for DCM (epsilon=8.93)"),
    ("Solvation", "CPCM(Toluene)", "CPCM implicit solvent model for toluene (epsilon=2.38)"),
    ("Solvation", "CPCM(THF)", "CPCM implicit solvent model for tetrahydrofuran (epsilon=7.58)"),
    ("Solvation", "CPCM(DMSO)", "CPCM implicit solvent model for dimethyl sulfoxide (epsilon=46.7)"),
    ("Solvation", "CPCM(Cyclohexane)", "CPCM implicit solvent model for cyclohexane (epsilon=2.02)"),
    ("Solvation", "CPCM(Benzene)", "CPCM implicit solvent model for benzene (epsilon=2.27)"),
    ("Solvation", "CPCM(Acetone)", "CPCM implicit solvent model for acetone (epsilon=20.7)"),
    ("Solvation", "CPCM(CCl4)", "CPCM implicit solvent model for carbon tetrachloride (epsilon=2.24)"),
    ("Solvation", "CPCM(DMF)", "CPCM implicit solvent model for dimethylformamide (epsilon=36.7)"),
    ("Solvation", "CPCM(Pyridine)", "CPCM implicit solvent model for pyridine (epsilon=12.4)"),
    ("Solvation", "SMD(Water)", "SMD continuum solvation model for water"),
    ("Solvation", "SMD(Acetonitrile)", "SMD continuum solvation model for acetonitrile"),
    ("Solvation", "SMD(Methanol)", "SMD continuum solvation model for methanol"),
    ("Solvation", "SMD(Ethanol)", "SMD continuum solvation model for ethanol"),
    ("Solvation", "SMD(Chloroform)", "SMD continuum solvation model for chloroform"),
    ("Solvation", "SMD(Dichloromethane)", "SMD continuum solvation model for dichloromethane"),
    ("Solvation", "SMD(Toluene)", "SMD continuum solvation model for toluene"),
    ("Solvation", "SMD(THF)", "SMD continuum solvation model for tetrahydrofuran"),
    ("Solvation", "SMD(DMSO)", "SMD continuum solvation model for dimethyl sulfoxide"),
    ("Solvation", "SMD(Cyclohexane)", "SMD continuum solvation model for cyclohexane"),
    ("Solvation", "SMD(Benzene)", "SMD continuum solvation model for benzene"),
    ("Solvation", "SMD(Acetone)", "SMD continuum solvation model for acetone"),
    ("Solvation", "SMD(CCl4)", "SMD continuum solvation model for carbon tetrachloride"),
    ("Solvation", "SMD(DMF)", "SMD continuum solvation model for dimethylformamide"),
    ("Solvation", "SMD(Pyridine)", "SMD continuum solvation model for pyridine"),
    ("Solvation", "ALPB(Water)", "Analytical linearized Poisson-Boltzmann model for water"),
    ("Solvation", "CPC(Water)", "Shorthand CPCM water model"),

    # --- Dispersion Corrections ---
    ("Dispersion", "D3BJ", "Grimme DFT-D3 with Becke-Johnson rational damping"),
    ("Dispersion", "D3Zero", "Grimme DFT-D3 with original zero damping function"),
    ("Dispersion", "D4", "Grimme DFT-D4 charge-dependent atomic dispersion correction"),
    ("Dispersion", "D2", "Grimme DFT-D2 empirical dispersion correction"),
    ("Dispersion", "NL", "Non-local van der Waals correlation (VV10)"),

    # --- RI & Integral Acceleration ---
    ("RI / Approximations", "RIJCOSX", "Resolution of identity for Coulomb and COSX for exchange (very fast)"),
    ("RI / Approximations", "RI-J", "Resolution of identity for Coulomb integrals"),
    ("RI / Approximations", "RI", "Standard resolution of identity for MP2/Coupled Cluster"),
    ("RI / Approximations", "COSX", "Chain-of-spheres exchange without RI-J"),
    ("RI / Approximations", "RI-SOMF(1X)", "Spin-orbit mean-field approximation for spin-orbit coupling"),
    ("RI / Approximations", "NoRI", "Disable all RI approximations (exact 4-center integrals)"),

    # --- Convergence & Numerical Grids ---
    ("Convergence & Grids", "TightSCF", "Tight energy and density convergence criteria for SCF"),
    ("Convergence & Grids", "VeryTightSCF", "Very tight SCF convergence criteria"),
    ("Convergence & Grids", "NormalSCF", "Standard SCF convergence criteria"),
    ("Convergence & Grids", "LooseSCF", "Loose SCF convergence criteria"),
    ("Convergence & Grids", "SloppySCF", "Sloppy SCF convergence (for rough initial geometries)"),
    ("Convergence & Grids", "ExtremeSCF", "Ultra-tight SCF convergence for benchmarking"),
    ("Convergence & Grids", "SlowConv", "Damping and level shifts for hard-to-converge SCF"),
    ("Convergence & Grids", "VerySlowConv", "Aggressive damping and orbital shifting for problematic SCF"),
    ("Convergence & Grids", "AutoTRAH", "Trust-region augmented Hessian SCF convergence accelerator"),
    ("Convergence & Grids", "SOSCF", "Second-order SCF orbital optimization"),
    ("Convergence & Grids", "KDIIS", "Krylov subspace accelerated DIIS convergence"),
    ("Convergence & Grids", "defgrid1", "Coarse DFT integration grid"),
    ("Convergence & Grids", "defgrid2", "Standard DFT integration grid (default in ORCA)"),
    ("Convergence & Grids", "defgrid3", "Enhanced DFT integration grid (recommended for meta-GGAs)"),
    ("Convergence & Grids", "Grid4", "Fine DFT integration grid"),
    ("Convergence & Grids", "Grid5", "Very fine DFT integration grid"),
    ("Convergence & Grids", "Grid6", "Ultra-fine DFT integration grid for bench-level accuracy"),
    ("Convergence & Grids", "NoGrid", "Disable numerical integration grids"),

    # --- Relativistic & Core Options ---
    ("Relativistic & Core", "ZORA", "Zeroth-Order Regular Approximation for relativistic effects"),
    ("Relativistic & Core", "DKH2", "Second-order Douglas-Kroll-Hess relativistic Hamiltonian"),
    ("Relativistic & Core", "DKH", "Standard Douglas-Kroll-Hess relativistic treatment"),
    ("Relativistic & Core", "X2C", "Exact two-component relativistic Hamiltonian"),
    ("Relativistic & Core", "NormalPNO", "Standard Domain-based Local Pair Natural Orbital cutoff (3.3e-7)"),
    ("Relativistic & Core", "TightPNO", "Tight PNO cutoff (1e-7) for high precision DLPNO calculations"),
    ("Relativistic & Core", "LoosePNO", "Loose PNO cutoff (1e-6) for rapid screening DLPNO calculations"),
    ("Relativistic & Core", "NoFrozenCore", "All-electron correlation calculation (no frozen core)"),
    ("Relativistic & Core", "FrozenCore", "Freeze standard chemical core orbitals in post-HF"),

    # --- Population Analysis & Orbitals ---
    ("Population & Output", "NBO", "Natural Bond Orbital population analysis (! NBO)"),
    ("Population & Output", "NPA", "Natural Population Analysis charges (! NPA)"),
    ("Population & Output", "CHELPG", "CHelpG atomic charges fitted to electrostatic potential"),
    ("Population & Output", "Hirshfeld", "Hirshfeld atomic population and charge analysis"),
    ("Population & Output", "Mulliken", "Mulliken population analysis"),
    ("Population & Output", "Loewdin", "Löwdin orthogonal population analysis"),
    ("Population & Output", "UCO", "Unrestricted Corresponding Orbitals for open-shell systems"),
    ("Population & Output", "UNO", "Unrestricted Natural Orbitals for broken-symmetry analysis"),
    ("Population & Output", "SOMO", "Singly Occupied Molecular Orbital analysis"),
    ("Population & Output", "FOD", "Fractional Occupancy Density analysis for multireference character"),
    ("Population & Output", "OptRot", "Optical Rotation calculation"),
    ("Population & Output", "NormalPrint", "Standard print verbosity"),
    ("Population & Output", "LargePrint", "Verbose output including orbital coefficients and eigenvectors"),
    ("Population & Output", "MiniPrint", "Minimal output verbosity"),
    ("Population & Output", "SmallPrint", "Compact output verbosity"),
    ("Population & Output", "KeepDens", "Keep electron density files on disk"),
    ("Population & Output", "KeepInts", "Keep two-electron integral files on disk"),

    # --- Advanced Physics & Spectroscopy ---
    ("Properties / Advanced", "NMR", "NMR chemical shielding tensors and spin-spin couplings"),
    ("Properties / Advanced", "EPR", "Electron Paramagnetic Resonance g-tensors and hyperfine couplings"),
    ("Properties / Advanced", "EPRNMR", "Combined EPR and NMR properties module"),
    ("Properties / Advanced", "ZFS", "Zero-field splitting parameters (D and E tensors)"),
    ("Properties / Advanced", "Polarizability", "Static and dynamic electric dipole polarizabilities"),
    ("Properties / Advanced", "Hyperpol", "First and second optical hyperpolarizabilities"),
    ("Properties / Advanced", "UKS", "Unrestricted Kohn-Sham for broken-symmetry singlet states"),
    ("Properties / Advanced", "MOREAD", "Read initial orbitals from a .gbw file (%moinp)"),
    ("Properties / Advanced", "TD-DFT", "Time-Dependent DFT excited state calculation"),
    ("Properties / Advanced", "TDA", "Tamm-Dancoff Approximation for excited states"),
    ("Properties / Advanced", "Singlets", "Calculate singlet excited states"),
    ("Properties / Advanced", "Triplets", "Calculate triplet excited states"),
]


