
import os
import json
import re
import numpy as np
from PyQt6.QtWidgets import (
    QDialog, QVBoxLayout, QHBoxLayout, QScrollArea, QWidget, 
    QGroupBox, QFormLayout, QSpinBox, QPushButton, QLabel, 
    QTextEdit, QLineEdit, QComboBox, QTabWidget, QSizePolicy, 
    QFontDialog, QMessageBox, QFileDialog, QInputDialog, QGridLayout)
from PyQt6.QtGui import QFont, QPalette, QColor
from PyQt6.QtCore import Qt

from rdkit import Chem
from rdkit.Chem import rdMolTransforms

from .highlighter import OrcaSyntaxHighlighter
from .keyword_builder import OrcaKeywordBuilderDialog
from . import PLUGIN_NAME, SETTINGS_FILE

class OrcaSetupDialogPro(QDialog):
    """
    ORCA Input Generator Pro
    """
    def __init__(self, parent=None, mol=None, filename=None):
        super().__init__(parent)
        self.setWindowTitle(PLUGIN_NAME)
        self.resize(1100, 800)
        self.setWindowFlags(self.windowFlags() | Qt.WindowType.WindowMinMaxButtonsHint)
        self.setSizeGripEnabled(True)
        self.mol = mol
        self.filename = filename
        self.ui_ready = False
        self.setup_ui()
        self.ui_ready = True
        self.load_presets_from_file()
        self.calc_initial_charge_mult()

    def setup_ui(self):
        main_layout = QVBoxLayout()
        
        # --- Horizontal Split Layer ---
        content_layout = QHBoxLayout()
        
        # --- Right Side: Settings (Scrollable) ---
        scroll_area = QScrollArea()
        scroll_area.setWidgetResizable(True)
        scroll_area.setFrameShape(QScrollArea.Shape.NoFrame)
        
        settings_container = QWidget()
        settings_layout = QVBoxLayout(settings_container)

        # --- 0. Preset Management ---
        preset_group = QGroupBox("Preset Management")
        preset_layout = QHBoxLayout()
        self.preset_combo = QComboBox()
        self.preset_combo.currentIndexChanged.connect(self.apply_selected_preset)
        preset_layout.addWidget(QLabel("Preset:"))
        preset_layout.addWidget(self.preset_combo, 1)
        self.btn_save_preset = QPushButton("Save New...")
        self.btn_save_preset.clicked.connect(self.save_preset_dialog)
        preset_layout.addWidget(self.btn_save_preset)
        self.btn_del_preset = QPushButton("Delete")
        self.btn_del_preset.clicked.connect(self.delete_preset)
        preset_layout.addWidget(self.btn_del_preset)
        preset_group.setLayout(preset_layout)
        settings_layout.addWidget(preset_group)

        # --- 1. Resource Configuration ---
        res_group = QGroupBox("Resources (%pal, %maxcore)")
        res_layout = QFormLayout()
        res_h1 = QHBoxLayout()
        self.nproc_spin = QSpinBox()
        self.nproc_spin.setRange(1, 128)
        self.nproc_spin.setValue(4)
        self.nproc_spin.valueChanged.connect(self.update_preview)
        btn_auto_proc = QPushButton("Auto")
        btn_auto_proc.setFixedWidth(50)
        btn_auto_proc.clicked.connect(self.auto_detect_nproc)
        res_h1.addWidget(self.nproc_spin)
        res_h1.addWidget(btn_auto_proc)
        res_layout.addRow("Processors:", res_h1)

        res_h2 = QHBoxLayout()
        self.mem_spin = QSpinBox()
        self.mem_spin.setRange(100, 999999)
        self.mem_spin.setValue(2000) 
        self.mem_spin.setSuffix(" MB")
        self.mem_spin.valueChanged.connect(self.update_preview)
        btn_auto_mem = QPushButton("Auto")
        btn_auto_mem.setFixedWidth(50)
        btn_auto_mem.clicked.connect(self.auto_detect_mem)
        res_h2.addWidget(self.mem_spin)
        res_h2.addWidget(btn_auto_mem)
        res_layout.addRow("MaxCore:", res_h2)
        res_group.setLayout(res_layout)
        settings_layout.addWidget(res_group)

        # --- 2. Simple Input Line ---
        kw_group = QGroupBox("Simple Input Line (!)")
        kw_layout = QVBoxLayout()
        kw_h_layout = QHBoxLayout()
        self.keywords_edit = QTextEdit("! B3LYP def2-SVP RIJCOSX Def2/J Opt Freq")
        self.keywords_edit.setFixedHeight(70)
        self.keywords_edit.textChanged.connect(self.update_preview)
        self.kw_highlighter = OrcaSyntaxHighlighter(self.keywords_edit.document())
        self.btn_route = QPushButton("Builder...")
        self.btn_route.clicked.connect(self.open_keyword_builder)
        kw_h_layout.addWidget(self.keywords_edit)
        kw_h_layout.addWidget(self.btn_route)
        kw_layout.addWidget(QLabel("Keywords:"))
        kw_layout.addLayout(kw_h_layout)
        self.comment_edit = QLineEdit("Generated by MoleditPy ORCA Input Generator Pro Plugin")
        self.comment_edit.textChanged.connect(self.update_preview)
        kw_layout.addWidget(QLabel("Comment:"))
        kw_layout.addWidget(self.comment_edit)
        kw_group.setLayout(kw_layout)
        settings_layout.addWidget(kw_group)

        # --- 3. Molecular State ---
        mol_group = QGroupBox("Molecular Specification")
        mol_layout = QHBoxLayout()
        self.charge_spin = QSpinBox()
        self.charge_spin.setRange(-10, 10)
        self.charge_spin.valueChanged.connect(self.validate_charge_mult)
        self.mult_spin = QSpinBox()
        self.mult_spin.setRange(1, 10)
        self.mult_spin.valueChanged.connect(self.validate_charge_mult)
        mol_layout.addWidget(QLabel("Charge:"))
        mol_layout.addWidget(self.charge_spin)
        mol_layout.addWidget(QLabel("Mult:"))
        mol_layout.addWidget(self.mult_spin)
        self.default_palette = self.charge_spin.palette()
        mol_group.setLayout(mol_layout)
        settings_layout.addWidget(mol_group)

        # --- 3b. Coordinate Format ---
        coord_group = QGroupBox("Coordinate Format")
        coord_layout = QHBoxLayout()
        self.coord_format_combo = QComboBox()
        self.coord_format_combo.addItems(["Cartesian (XYZ)", "Internal (* int)", "Internal (* gzmt)"])
        self.coord_format_combo.currentIndexChanged.connect(self.update_preview)
        coord_layout.addWidget(self.coord_format_combo)
        coord_group.setLayout(coord_layout)
        settings_layout.addWidget(coord_group)

        # --- 4. Advanced/Blocks ---
        adv_group = QGroupBox("Advanced Blocks")
        adv_layout = QVBoxLayout()
        blk_h_layout = QHBoxLayout()
        self.block_combo = QComboBox()
        self.block_combo.addItems([
            "Select Block to Insert...",
            "%output (Basis/MOs)",
            "%eprnmr (NMR/J-coupling)",
            "%scf ... end",
            "%geom ... end",
            "%elprop ... end",
            "%plots ... end",
            "%tddft ... end",
            "%cis ... end", 
            "%mrci ... end",
            "%casscf ... end"
        ])
        blk_h_layout.addWidget(self.block_combo, 1)
        self.btn_insert_block = QPushButton("Insert")
        self.btn_insert_block.clicked.connect(self.insert_block_template)
        blk_h_layout.addWidget(self.btn_insert_block)
        adv_layout.addLayout(blk_h_layout)
        self.adv_tabs = QTabWidget()
        self.adv_tabs.setFixedHeight(120)
        self.adv_edit = QTextEdit()
        self.adv_edit.textChanged.connect(self.update_preview)
        self.adv_tabs.addTab(self.adv_edit, "Pre-Coord")
        self.post_adv_edit = QTextEdit()
        self.post_adv_edit.textChanged.connect(self.update_preview)
        self.adv_tabs.addTab(self.post_adv_edit, "Post-Coord")
        adv_layout.addWidget(self.adv_tabs)
        adv_group.setLayout(adv_layout)
        settings_layout.addWidget(adv_group)

        settings_layout.addStretch()
        scroll_area.setWidget(settings_container)
        content_layout.addWidget(scroll_area, 3) # Left side settings

        # --- Right Side: Preview ---
        preview_group = QGroupBox("Input Preview")
        preview_layout = QVBoxLayout()
        self.preview_text = QTextEdit()
        self.preview_text.setReadOnly(False)
        self.preview_text.setFont(QFont("Courier New", 10))
        self.preview_text.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        self.highlighter = OrcaSyntaxHighlighter(self.preview_text.document())
        preview_layout.addWidget(self.preview_text)
        btn_refresh = QPushButton("Reset/Refresh Preview")
        btn_refresh.clicked.connect(self.update_preview)
        preview_layout.addWidget(btn_refresh)
        preview_group.setLayout(preview_layout)
        content_layout.addWidget(preview_group, 4) # Right side preview
        
        main_layout.addLayout(content_layout)

        # --- Save Button ---
        self.save_btn = QPushButton("Save ORCA Input File...")
        self.save_btn.clicked.connect(self.save_file)
        self.save_btn.setStyleSheet("font-weight: bold; padding: 8px; font-size: 14px;")
        main_layout.addWidget(self.save_btn)
        
        self.setLayout(main_layout)
        self.update_preview()
        
    def update_preview(self):
        if not getattr(self, 'ui_ready', False):
            return
        self.preview_text.setText(self.generate_input_content())

    def auto_detect_nproc(self):
        try:
            import psutil
            cpus = psutil.cpu_count(logical=False)
        except:
            cpus = os.cpu_count()
            
        if cpus:
            self.nproc_spin.setValue(cpus)

    def auto_detect_mem(self):
        # Default fallback
        total_mb = 8000
        try:
            import psutil
            # Total system memory
            total_mb = psutil.virtual_memory().total // (1024 * 1024)
        except:
             pass
        
        # Use roughly 75-80% of total memory to be safe, divided by nprocs
        nprocs = self.nproc_spin.value()
        rec_core = int((total_mb * 0.80) / nprocs)
        self.mem_spin.setValue(max(500, rec_core))

    def preview_file(self):
        # Legacy stub
        self.update_preview()

    def save_file(self):
        # 1. 座標データの取得 (Check for error first)
        coord_style = self.coord_format_combo.currentText()
        if "XYZ" in coord_style:
            lines = self.get_coords_lines()
        elif "gzmt" in coord_style:
             lines = self.get_zmatrix_gzmt_lines()
        else:
             lines = self.get_zmatrix_standard_lines()

        if any("Error" in l for l in lines):
            err = "\\n".join(l for l in lines if "Error" in l)
            QMessageBox.critical(self, "Error", f"Coordinate Generation Failed:\\n{err}")
            return

        # 2. ファイル保存ダイアログ
        default_dir = os.getcwd()
        default_base = "orca_job.inp"
        
        if self.filename:
            # Check if it's an absolute path
            if os.path.isabs(self.filename):
                default_dir = os.path.dirname(self.filename)
                default_base = os.path.splitext(os.path.basename(self.filename))[0] + ".inp"
            else:
                # It might be just a filename/title
                default_base = os.path.splitext(self.filename)[0] + ".inp"
        
        # Ensure default_base doesn't have invalid chars
        import re
        default_base = re.sub(r'[\\/*?Source:"<>|]', "_", default_base).strip()
        if not default_base: default_base = "orca_job.inp"

        # Combine
        default_full = os.path.join(default_dir, default_base)
        
        file_path, _ = QFileDialog.getSaveFileName(
            self, "Save ORCA Input", default_full, "ORCA Input (*.inp);;All Files (*)"
        )

        if file_path:
            try:
                # Use content from preview (editable)
                content = self.preview_text.toPlainText()
                
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(content)

                QMessageBox.information(self, "Success", f"File saved:\\n{file_path}")
                #QMessageBox.information(self, "Success", f"File saved:\n{file_path}")
                # Do not close automatically
                # self.accept()
            except Exception as e:
                QMessageBox.critical(self, "Error", f"Failed to save file:\n{str(e)}")

    def insert_block_template(self):
        txt = self.block_combo.currentText()
        if "Select" in txt: return
        
        template = ""
        if "%scf" in txt:
             template = "%scf\n MaxIter 125\nend\n"
        elif "%output" in txt:
             template = "%output\n  Print[P_Basis] 2  # Required for Basis Set parsing\n  Print[P_Mos] 1    # Ensure MO coefficients are printed\nend\n"
        elif "%geom" in txt:
             template = "%geom\n  Calc_Hess   true\n  Recalc_Hess 1\n  MaxIter     256\nend\n"
        elif "%elprop" in txt:
             template = "%elprop\n Dipole True\n Quadrupole True\nend\n"
        elif "%plots" in txt:
             template = "%plots\n Format Gaussian_Cube\nend\n"
        elif "%tddft" in txt:
             template = (
                 "%tddft\n"
                 "  NRoots 10       # Number of excited states\n"
                 "  MaxDim 10       # Max dimension of expansion space\n"
                 "  TDA true        # Tamm-Dancoff Approximation (true/false)\n"
                 "  IRoot 1         # State of interest for gradient properties\n"
                 "  Triplets false  # Calculate triplet states\n"
                 "  Singlets true   # Calculate singlet states\n"
                 "  DoQuad true     # Compute quadrupole intensities\n"
                 "end\n"
             )
        elif "%cis" in txt:
             template = "%cis\n NRoots 10\nend\n"
        elif "%mrci" in txt:
             template = "%mrci\n NewBlocks 1 1\nend\n"
        elif "%casscf" in txt:
             template = "%casscf\n Nel 2\n Norb 2\n Mult 1\nend\n"
        elif "%eprnmr" in txt:
             template = "%eprnmr\n  NUCLEI = ALL H {SHIFT, SSALL} # Required for J-coupling (nmrsim)\nend\n"
             # Switch to Post-Coordinate tab automatically
             self.adv_tabs.setCurrentWidget(self.post_adv_edit)
        
        current_widget = self.adv_tabs.currentWidget()
        if isinstance(current_widget, QTextEdit):
            cursor = current_widget.textCursor()
            cursor.insertText(template)

    def open_keyword_builder(self):
        # Pass mol and main_window (self.parent()) for picking
        if hasattr(self, "builder_dialog") and self.builder_dialog is not None:
            # If it already exists, just show it. 
            # We don't want to re-create it as it would lose 
            # the constraint table state (unless we re-parse everything perfectly).
            self.builder_dialog.show()
            self.builder_dialog.raise_()
            self.builder_dialog.activateWindow()
            return

        self.builder_dialog = OrcaKeywordBuilderDialog(self, self.keywords_edit.toPlainText(), mol=self.mol, main_window=self.parent())
        self.builder_dialog.finished.connect(lambda r: self.on_builder_finished(r))
        self.builder_dialog.show()

    def on_builder_finished(self, result):
        if result == QDialog.DialogCode.Accepted:
            if hasattr(self, "builder_dialog"):
                self.keywords_edit.setPlainText(self.builder_dialog.get_route())
        
        self.update_preview()

    def get_coords_lines(self):
        if not self.mol: return []
        lines = []
        try:
            conf = self.mol.GetConformer()
            for i in range(self.mol.GetNumAtoms()):
                pos = conf.GetAtomPosition(i)
                atom = self.mol.GetAtomWithIdx(i)
                lines.append(f"  {atom.GetSymbol(): <4} {pos.x: >12.6f} {pos.y: >12.6f} {pos.z: >12.6f}")
        except Exception as e:
            return [f"# Error: {e}"]
        return lines

    def _build_zmatrix_data(self):
        """Helper to build Z-Matrix connectivity and values."""
        if not self.mol: return None
        try:
            atoms = list(self.mol.GetAtoms())
            conf = self.mol.GetConformer()
            
            def get_dist(i, j): return rdMolTransforms.GetBondLength(conf, i, j)
            def get_angle(i, j, k): return rdMolTransforms.GetAngleDeg(conf, i, j, k)
            def get_dihedral(i, j, k, l): return rdMolTransforms.GetDihedralDeg(conf, i, j, k, l)
            
            defined = []
            z_data = [] # List of dicts for each atom
            
            for i, atom in enumerate(atoms):
                symbol = atom.GetSymbol()
                
                # Atom 0
                if i == 0:
                    z_data.append({"symbol": symbol, "refs": []})
                    defined.append(i)
                    continue
                
                # Find neighbors in defined set
                current_idx = atom.GetIdx()
                neighbors = [n.GetIdx() for n in atom.GetNeighbors()]
                candidates = [n for n in neighbors if n in defined]
                if not candidates: candidates = defined[:] # Fallback
                
                refs = []
                # Ref 1 (Distance)
                if candidates: refs.append(candidates[-1])
                else: refs.append(0)
                
                # Ref 2 (Angle)
                candidates_2 = [x for x in defined if x != refs[0]]
                if candidates_2: refs.append(candidates_2[-1])
                
                # Ref 3 (Dihedral)
                candidates_3 = [x for x in defined if x not in refs]
                if candidates_3: refs.append(candidates_3[-1])
                
                # Calculate Values
                row = {"symbol": symbol, "refs": [], "values": []}
                
                if len(refs) >= 1:
                    row["refs"].append(refs[0]) # 0-based index for calculation
                    row["values"].append(get_dist(i, refs[0]))
                
                if len(refs) >= 2:
                    row["refs"].append(refs[1])
                    row["values"].append(get_angle(i, refs[0], refs[1]))
                
                if len(refs) >= 3:
                    row["refs"].append(refs[2])
                    row["values"].append(get_dihedral(i, refs[0], refs[1], refs[2]))
                
                z_data.append(row)
                defined.append(i)
                
            return z_data
        except Exception as e:
            raise e

    def get_zmatrix_standard_lines(self):
        """
        Generates * int style lines.
        Format: Symbol Ref1 Ref2 Ref3 R Angle Dihed
        Refs are 1-based integers. Missing refs/values are 0/0.0.
        """
        try:
            data = self._build_zmatrix_data()
            if not data: return []
            
            lines = []
            for i, row in enumerate(data):
                symbol = row["symbol"]
                
                # Prepare 3 refs (1-based) and 3 values
                refs_out = [0, 0, 0]
                vals_out = [0.0, 0.0, 0.0]
                
                current_refs = row["refs"]
                current_vals = row.get("values", [])
                
                for k in range(min(3, len(current_refs))):
                    refs_out[k] = current_refs[k] + 1 # Convert to 1-based
                    vals_out[k] = current_vals[k]
                    
                line = f"  {symbol: <3} {refs_out[0]: >3} {refs_out[1]: >3} {refs_out[2]: >3} " \
                       f"{vals_out[0]: >10.6f} {vals_out[1]: >10.6f} {vals_out[2]: >10.6f}"
                lines.append(line)
            return lines
        except Exception as e:
            return [f"# Error generating Standard Z-Matrix: {e}"]

    def get_zmatrix_gzmt_lines(self):
        """
        Generates * gzmt style lines (Compact).
        Format: Symbol Ref1 R Ref2 Angle Ref3 Dihed
        Refs are 1-based.
        """
        try:
            data = self._build_zmatrix_data()
            if not data: return []
            
            lines = []
            for i, row in enumerate(data):
                symbol = row["symbol"]
                line = f"  {symbol: <3}"
                
                current_refs = row["refs"]
                current_vals = row.get("values", [])
                
                # Z-Matrix logic:
                # Atom 1: Symbol
                # Atom 2: Symbol Ref1 R
                # Atom 3: Symbol Ref1 R Ref2 A
                # Atom 4: Symbol Ref1 R Ref2 A Ref3 D
                
                if i == 0:
                    pass
                else:
                    count = len(current_refs)
                    if count >= 1:
                        line += f"  {current_refs[0] + 1: >3} {current_vals[0]: .6f}"
                    if count >= 2:
                        line += f"  {current_refs[1] + 1: >3} {current_vals[1]: .6f}"
                    if count >= 3:
                        line += f"  {current_refs[2] + 1: >3} {current_vals[2]: .6f}"
                
                lines.append(line)
            return lines
        except Exception as e:
            return [f"# Error generating GZMT Z-Matrix: {e}"]

    def generate_input_content(self):
        """Generates the full content of the input file as a string."""
        content = []
        
        comment = self.comment_edit.text().strip()
        if comment:
            content.append(f"# {comment}")
        
        # 1. Resources (from UI) 
        nprocs = self.nproc_spin.value()
        if nprocs > 1:
            content.append(f"%pal nprocs {nprocs} end")
        content.append(f"%maxcore {self.mem_spin.value()}")
        
        # 2. KeywordsLine (!)
        kw = self.keywords_edit.toPlainText().strip()
        if kw:
            if not kw.startswith("!"): kw = "! " + kw
            content.append(f"\n{kw}")
        
        # 3. Advanced Blocks (%)
        adv = self.adv_edit.toPlainText().strip()
        if adv:
            content.append(f"\n{adv}")
            
        # 4. Post-Coordinate Blocks (%)
        adv_post = self.post_adv_edit.toPlainText().strip()
        if adv_post:
            content.append(f"\n{adv_post}")

        # --- Coordinates ---
        is_cartesian = "Cartesian" in self.coord_format_combo.currentText()
        content.append("") # Spacer
        
        charge = self.charge_spin.value()
        mult = self.mult_spin.value()
        
        if is_cartesian:
            content.append(f"* xyz {charge} {mult}")
            content.extend(self.get_coords_lines())
            content.append("*")
        else:
            is_gzmt = "gzmt" in self.coord_format_combo.currentText()
            if is_gzmt:
                header = "* gzmt"
                zmat_lines = self.get_zmatrix_gzmt_lines()
            else:
                header = "* int"
                zmat_lines = self.get_zmatrix_standard_lines()
                
            if any("Error" in line for line in zmat_lines):
                content.append(f"# ERROR: Z-Matrix generation failed. Falling back to XYZ.")
                content.append(f"* xyz {charge} {mult}")
                content.extend(self.get_coords_lines())
                content.append("*")
            else:
                content.append(f"{header} {charge} {mult}")
                content.extend(zmat_lines)
                content.append("*")

        # 5. Final Consolidation (Merge blocks, dedup MaxIter etc.)
        full_text = "\n".join(content)
        return self.consolidate_orca_blocks(full_text)

    def consolidate_orca_blocks(self, text):
        """
        Final pass to merge redundant %geom blocks and deduplicate MaxIter.
        Only merges top-level blocks.
        """
        import re
        lines = text.splitlines()
        
        last_pal = None
        last_maxcore = None
        all_geom_inner = []
        others = []
        
        idx = 0
        while idx < len(lines):
            line = lines[idx]
            s = line.strip()
            
            # --- %pal / %maxcore ---
            if s.lower().startswith("%pal"):
                # Handle one-liner: %pal nprocs 4 end
                if " end" in s.lower() or s.lower().endswith("end"):
                    last_pal = s
                    idx += 1
                    continue
                # Handle multi-liner (rare for %pal but possible)
                last_pal = line
                idx += 1
                while idx < len(lines):
                    l_inner = lines[idx]
                    last_pal += "\n" + l_inner
                    if l_inner.strip().lower() == "end" and not l_inner.startswith(" "):
                        break
                    idx += 1
                idx += 1
                continue
                
            if s.lower().startswith("%maxcore"):
                last_maxcore = s
                idx += 1
                continue
            
            # --- %geom (Merge targets) ---
            if s.lower().startswith("%geom"):
                # One-liner?
                if " end" in s.lower() or s.lower().endswith("end"):
                    m = re.match(r"^%geom\s+(.*)\s+end", s, re.I)
                    if m: all_geom_inner.append(m.group(1))
                    idx += 1
                    continue
                # Multi-liner
                idx += 1
                while idx < len(lines):
                    l_inner = lines[idx]
                    if l_inner.strip().lower() == "end" and not l_inner.startswith(" "):
                        break
                    all_geom_inner.append(l_inner)
                    idx += 1
                idx += 1
                continue
            
            # --- Default ---
            others.append(line)
            idx += 1

        # Deduplicate keywords within merged %geom parts
        final_lines = []
        if last_pal: final_lines.append(last_pal)
        if last_maxcore: final_lines.append(last_maxcore)
        
        # Keep keywords (starting with !) and comments at top
        header_lines = []
        coord_lines = []
        for l in others:
            s_l = l.strip()
            if s_l.startswith("!") or s_l.startswith("#") or not s_l:
                header_lines.append(l)
            else:
                coord_lines.append(l)
        
        final_lines.extend(header_lines)
        
        # Process merged geom block
        if all_geom_inner:
            final_lines.append("%geom")
            # Deduplicate MaxIter only
            k_map = {}
            filtered = []
            for l in all_geom_inner:
                m = re.match(r"^\s*(maxiter|nroots|maxdim)\b\s+(.*)$", l, re.I)
                if m:
                    k = m.group(1).lower()
                    k_map[k] = l # keep last
                else:
                    filtered.append(l)
            
            # Add deduped keys
            for k in k_map: final_lines.append(k_map[k])
            final_lines.extend(filtered)
            final_lines.append("end")
        
        final_lines.extend(coord_lines)
        return "\n".join(final_lines)

    # --- Preset Management ---
    def load_presets_from_file(self):
        self.presets_data = {}
        if os.path.exists(SETTINGS_FILE):
            try:
                with open(SETTINGS_FILE, 'r', encoding='utf-8') as f:
                    self.presets_data = json.load(f)
            except Exception as e:
                print(f"Error loading presets: {e}")
        
        if "Default" not in self.presets_data:
            self.presets_data["Default"] = {
                "nproc": 4, "maxcore": 2000, 
                "route": "! B3LYP def2-SVP RIJCOSX Def2/J Opt Freq", "adv": "", "adv_post": ""
            }
        
        self.update_preset_combo()

    def update_preset_combo(self):
        current = self.preset_combo.currentText()
        self.preset_combo.blockSignals(True)
        self.preset_combo.clear()
        self.preset_combo.addItems(sorted(self.presets_data.keys()))
        if current in self.presets_data:
            self.preset_combo.setCurrentText(current)
        elif "Default" in self.presets_data:
            self.preset_combo.setCurrentText("Default")
        self.preset_combo.blockSignals(False)
        self.apply_selected_preset()

    def apply_selected_preset(self):
        name = self.preset_combo.currentText()
        if name not in self.presets_data: return
        data = self.presets_data[name]
        self.nproc_spin.setValue(data.get("nproc", 4))
        self.mem_spin.setValue(data.get("maxcore", 2000))
        self.keywords_edit.setText(data.get("route", "! B3LYP def2-SVP RIJCOSX Def2/J Opt Freq"))
        self.adv_edit.setPlainText(data.get("adv", ""))
        self.post_adv_edit.setPlainText(data.get("adv_post", ""))
        self.update_preview()

    def save_preset_dialog(self):
        name, ok = QInputDialog.getText(self, "Save Preset", "Preset Name:")
        if ok and name:
            self.presets_data[name] = {
                "nproc": self.nproc_spin.value(),
                "maxcore": self.mem_spin.value(),
                "route": self.keywords_edit.toPlainText(),
                "adv": self.adv_edit.toPlainText(),
                "adv_post": self.post_adv_edit.toPlainText()
            }
            self.save_presets_to_file()
            self.update_preset_combo()
            self.preset_combo.setCurrentText(name)

    def delete_preset(self):
        name = self.preset_combo.currentText()
        if name == "Default":
             QMessageBox.warning(self, "Warning", "Cannot delete Default preset.")
             return
        confirm = QMessageBox.question(self, "Confirm", f"Delete preset '{name}'?")
        if confirm == QMessageBox.StandardButton.Yes:
            del self.presets_data[name]
            self.save_presets_to_file()
            self.update_preset_combo()

    def save_presets_to_file(self):
        try:
            with open(SETTINGS_FILE, 'w', encoding='utf-8') as f:
                json.dump(self.presets_data, f, indent=4)
        except Exception as e:
            QMessageBox.warning(self, "Error", f"Failed to save presets: {e}")

    # --- Charge/Mult Logic ---
    def calc_initial_charge_mult(self):
        if not self.mol: return
        try:
            try: charge = Chem.GetFormalCharge(self.mol)
            except: charge = 0
            num_radical = sum(atom.GetNumRadicalElectrons() for atom in self.mol.GetAtoms())
            mult = num_radical + 1
            self.charge_spin.setValue(int(charge))
            self.mult_spin.setValue(int(mult))
            self.validate_charge_mult()
        except: pass

    def validate_charge_mult(self):
        if not self.mol: return
        try:
            charge = self.charge_spin.value()
            mult = self.mult_spin.value()
            total_protons = sum(atom.GetAtomicNum() for atom in self.mol.GetAtoms())
            total_electrons = total_protons - charge
            is_valid = (total_electrons % 2 == 0 and mult % 2 != 0) or \
                       (total_electrons % 2 != 0 and mult % 2 == 0)
            if is_valid:
                self.charge_spin.setPalette(self.default_palette)
                self.mult_spin.setPalette(self.default_palette)
            else:
                p = self.charge_spin.palette()
                p.setColor(QPalette.ColorRole.Base, QColor("#FFDDDD"))
                p.setColor(QPalette.ColorRole.Text, Qt.GlobalColor.red)
                self.charge_spin.setPalette(p)
                self.mult_spin.setPalette(p)
            self.update_preview()
        except: pass

    def closeEvent(self, event):
        if hasattr(self, "builder_dialog") and self.builder_dialog:
            self.builder_dialog.close()
        super().closeEvent(event)

    def keyPressEvent(self, event):
        if event.key() == Qt.Key.Key_Escape:
            focused = self.focusWidget()
            if isinstance(focused, (QLineEdit, QComboBox, QSpinBox, QTextEdit)):
                focused.clearFocus()
                return
        super().keyPressEvent(event)



