import os
import json
from PyQt6.QtWidgets import (
    QDialog,
    QVBoxLayout,
    QHBoxLayout,
    QScrollArea,
    QWidget,
    QGroupBox,
    QFormLayout,
    QSpinBox,
    QPushButton,
    QLabel,
    QTextEdit,
    QLineEdit,
    QComboBox,
    QTabWidget,
    QSizePolicy,
    QMessageBox,
    QFileDialog,
    QInputDialog,
    QCheckBox,
)
from PyQt6.QtGui import QFont, QPalette, QColor
from PyQt6.QtCore import Qt

from rdkit import Chem
from rdkit.Chem import rdMolTransforms

from .highlighter import OrcaSyntaxHighlighter
from .keyword_builder import OrcaKeywordBuilderDialog
from . import PLUGIN_NAME, PLUGIN_VERSION, SETTINGS_FILE
import logging


class OrcaSetupDialogPro(QDialog):
    """
    ORCA Input Generator Pro
    """

    def __init__(
        self,
        parent=None,
        mol=None,
        filename=None,
        persistent_settings=None,
        mark_modified=None,
    ):
        super().__init__(parent)
        self.setWindowTitle(f"{PLUGIN_NAME} v{PLUGIN_VERSION}")
        self.resize(1100, 800)
        self.setWindowFlags(self.windowFlags() | Qt.WindowType.WindowMinMaxButtonsHint)
        self.setSizeGripEnabled(True)
        self.mol = mol
        self.filename = filename
        self.persistent_settings = persistent_settings
        self.mark_modified = mark_modified
        self.ui_ready = False
        self.setup_ui()
        self.load_presets_from_file()
        self.load_persistent_settings()
        self.calc_initial_charge_mult()
        self.ui_ready = True

    def setup_ui(self):
        main_layout = QVBoxLayout()

        # --- Horizontal Split Layer ---
        content_layout = QHBoxLayout()

        # --- Right Side: Settings (Scrollable) ---
        scroll_area = QScrollArea()
        scroll_area.setWidgetResizable(True)
        scroll_area.setFrameShape(QScrollArea.Shape.NoFrame)

        settings_container = QWidget()
        settings_layout = QVBoxLayout(settings_container)

        # --- 0. Preset Management ---
        preset_group = QGroupBox("Preset Management")
        preset_layout = QHBoxLayout()
        self.preset_combo = QComboBox()
        self.preset_combo.currentIndexChanged.connect(self.apply_selected_preset)
        preset_layout.addWidget(QLabel("Preset:"))
        preset_layout.addWidget(self.preset_combo, 1)
        self.btn_save_preset = QPushButton("Save New...")
        self.btn_save_preset.clicked.connect(self.save_preset_dialog)
        preset_layout.addWidget(self.btn_save_preset)
        self.btn_del_preset = QPushButton("Delete")
        self.btn_del_preset.clicked.connect(self.delete_preset)
        preset_layout.addWidget(self.btn_del_preset)
        preset_group.setLayout(preset_layout)
        settings_layout.addWidget(preset_group)

        # --- 0.5 Comment Section ---
        comment_group = QGroupBox("Comment (#)")
        comment_layout = QVBoxLayout()
        self.comment_edit = QLineEdit(
            "Generated by MoleditPy ORCA Input Generator Pro Plugin"
        )
        self.comment_edit.textChanged.connect(self.update_preview)
        comment_layout.addWidget(self.comment_edit)
        comment_group.setLayout(comment_layout)
        settings_layout.addWidget(comment_group)

        # --- 1. Resource Configuration ---
        res_group = QGroupBox("Resources (%pal, %maxcore)")
        res_layout = QFormLayout()
        res_h1 = QHBoxLayout()
        self.nproc_spin = QSpinBox()
        self.nproc_spin.setRange(1, 128)
        self.nproc_spin.setValue(4)
        self.nproc_spin.valueChanged.connect(self.update_preview)
        btn_auto_proc = QPushButton("Auto")
        btn_auto_proc.setFixedWidth(50)
        btn_auto_proc.clicked.connect(self.auto_detect_nproc)
        res_h1.addWidget(self.nproc_spin)
        res_h1.addWidget(btn_auto_proc)
        res_layout.addRow("Processors:", res_h1)

        res_h2 = QHBoxLayout()
        self.mem_spin = QSpinBox()
        self.mem_spin.setRange(100, 999999)
        self.mem_spin.setValue(2000)
        self.mem_spin.setSuffix(" MB")
        self.mem_spin.valueChanged.connect(self.update_preview)
        btn_auto_mem = QPushButton("Auto")
        btn_auto_mem.setFixedWidth(50)
        btn_auto_mem.clicked.connect(self.auto_detect_mem)
        res_h2.addWidget(self.mem_spin)
        res_h2.addWidget(btn_auto_mem)
        res_layout.addRow("MaxCore:", res_h2)
        res_group.setLayout(res_layout)
        settings_layout.addWidget(res_group)

        # --- 2. Simple Input Line ---
        kw_group = QGroupBox("Simple Input Line (!)")
        kw_layout = QVBoxLayout()
        kw_h_layout = QHBoxLayout()
        self.keywords_edit = QTextEdit("! B3LYP def2-SVP RIJCOSX Def2/J Opt Freq")
        self.keywords_edit.setFixedHeight(70)
        self.keywords_edit.textChanged.connect(self.update_preview)
        self.kw_highlighter = OrcaSyntaxHighlighter(self.keywords_edit.document())
        self.btn_route = QPushButton("Builder...")
        self.btn_route.clicked.connect(self.open_keyword_builder)
        kw_h_layout.addWidget(self.keywords_edit)
        kw_h_layout.addWidget(self.btn_route)
        kw_layout.addWidget(QLabel("Keywords:"))
        kw_layout.addLayout(kw_h_layout)
        kw_group.setLayout(kw_layout)
        settings_layout.addWidget(kw_group)

        # --- 3. Molecular State ---
        mol_group = QGroupBox("Molecular Specification")
        mol_layout = QHBoxLayout()
        self.charge_spin = QSpinBox()
        self.charge_spin.setRange(-10, 10)
        self.charge_spin.valueChanged.connect(self.validate_charge_mult)
        self.mult_spin = QSpinBox()
        self.mult_spin.setRange(1, 10)
        self.mult_spin.valueChanged.connect(self.validate_charge_mult)
        mol_layout.addWidget(QLabel("Charge:"))
        mol_layout.addWidget(self.charge_spin)
        mol_layout.addWidget(QLabel("Mult:"))
        mol_layout.addWidget(self.mult_spin)
        self.default_palette = self.charge_spin.palette()
        mol_group.setLayout(mol_layout)
        settings_layout.addWidget(mol_group)

        # --- 3b. Coordinate Format ---
        coord_group = QGroupBox("Coordinate Format")
        coord_layout = QHBoxLayout()
        self.coord_format_combo = QComboBox()
        self.coord_format_combo.addItems(
            ["Cartesian (XYZ)", "Internal (* int)", "Internal (* gzmt)"]
        )
        self.coord_format_combo.currentIndexChanged.connect(self.update_preview)
        coord_layout.addWidget(self.coord_format_combo)
        coord_group.setLayout(coord_layout)
        settings_layout.addWidget(coord_group)

        # --- 4. Advanced/Blocks ---
        adv_group = QGroupBox("Advanced Blocks")
        adv_layout = QVBoxLayout()
        blk_h_layout = QHBoxLayout()
        self.block_combo = QComboBox()
        self.block_combo.addItems(
            [
                "Select Block to Insert...",
                "%output (Basis/MOs)",
                "%eprnmr (NMR/J-coupling)",
                "%scf ... end",
                "%geom ... end",
                "%elprop ... end",
                "%plots ... end",
                "%tddft ... end",
                "%cis ... end",
                "%mrci ... end",
                "%casscf ... end",
            ]
        )
        blk_h_layout.addWidget(self.block_combo, 1)
        self.btn_insert_block = QPushButton("Insert")
        self.btn_insert_block.clicked.connect(self.insert_block_template)
        blk_h_layout.addWidget(self.btn_insert_block)
        adv_layout.addLayout(blk_h_layout)
        self.adv_tabs = QTabWidget()
        self.adv_tabs.setFixedHeight(120)
        self.adv_edit = QTextEdit()
        self.adv_edit.textChanged.connect(self.update_preview)
        self.adv_tabs.addTab(self.adv_edit, "Pre-Coord")
        self.post_adv_edit = QTextEdit()
        self.post_adv_edit.textChanged.connect(self.update_preview)
        self.adv_tabs.addTab(self.post_adv_edit, "Post-Coord")
        adv_layout.addWidget(self.adv_tabs)
        adv_group.setLayout(adv_layout)
        settings_layout.addWidget(adv_group)

        settings_layout.addStretch()
        scroll_area.setWidget(settings_container)
        content_layout.addWidget(scroll_area, 3)  # Left side settings

        # --- Right Side: Preview ---
        preview_group = QGroupBox("Input Preview")
        preview_layout = QVBoxLayout()
        self.preview_text = QTextEdit()
        self.preview_text.setReadOnly(False)
        self.preview_text.setFont(QFont("Courier New", 10))
        self.preview_text.setSizePolicy(
            QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding
        )
        self.highlighter = OrcaSyntaxHighlighter(self.preview_text.document())
        preview_layout.addWidget(self.preview_text)
        btn_refresh = QPushButton("Reset/Refresh Preview")
        btn_refresh.clicked.connect(self.update_preview)
        preview_layout.addWidget(btn_refresh)
        preview_group.setLayout(preview_layout)
        content_layout.addWidget(preview_group, 4)  # Right side preview

        main_layout.addLayout(content_layout)

        # --- Bottom Options ---
        cb_layout = QHBoxLayout()
        cb_layout.addStretch()
        self.auto_suffix_cb = QCheckBox("Auto Suffix")
        self.auto_suffix_cb.setChecked(True)
        self.auto_suffix_cb.stateChanged.connect(self.update_preview)
        self.auto_suffix_cb.stateChanged.connect(self.save_global_settings)
        cb_layout.addWidget(self.auto_suffix_cb)
        main_layout.addLayout(cb_layout)

        # --- Bottom Buttons ---
        btn_layout = QHBoxLayout()
        self.btn_close = QPushButton("Close")
        self.btn_close.clicked.connect(self.reject)
        self.btn_close.setStyleSheet("padding: 8px; font-size: 14px;")
        self.btn_close.setSizePolicy(
            QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed
        )

        self.save_btn = QPushButton("Save ORCA Input File...")
        self.save_btn.clicked.connect(self.save_file)
        self.save_btn.setStyleSheet("font-weight: bold; padding: 8px; font-size: 14px;")
        self.save_btn.setSizePolicy(
            QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed
        )

        btn_layout.addWidget(self.btn_close)
        btn_layout.addWidget(self.save_btn)

        main_layout.addLayout(btn_layout)

        self.setLayout(main_layout)
        self.update_preview()

    def _resolve_live_mol(self):
        """Prefer the currently active molecule in the 3D manager."""
        try:
            mw = self.parent()
            if mw and hasattr(mw, "view_3d_manager"):
                live = mw.view_3d_manager.current_mol
                if live is not None:
                    self.mol = live
        except Exception as _e:
            logging.warning("[main_dialog.py:238] silenced: %s", _e)
        return self.mol

    def update_preview(self):
        if not getattr(self, "ui_ready", False):
            return

        # Update persistent settings
        if self.persistent_settings is not None:
            p = self.persistent_settings
            p["nproc"] = self.nproc_spin.value()
            p["maxcore"] = self.mem_spin.value()
            p["route"] = self.keywords_edit.toPlainText()
            p["adv"] = self.adv_edit.toPlainText()
            p["adv_post"] = self.post_adv_edit.toPlainText()
            p["comment"] = self.comment_edit.text()
            p["coord_format"] = self.coord_format_combo.currentText()

        self.preview_text.setText(self.generate_input_content())

        if self.mark_modified is not None:
            try:
                self.mark_modified()
            except Exception as _e:
                logging.warning("[main_dialog.py] mark_modified failed: %s", _e)

    def load_persistent_settings(self):
        if not self.persistent_settings:
            return
        # Temporarily block signals to avoid redundant updates
        self.blockSignals(True)
        try:
            p = self.persistent_settings
            if "nproc" in p:
                self.nproc_spin.setValue(p["nproc"])
            if "maxcore" in p:
                self.mem_spin.setValue(p["maxcore"])
            if "route" in p:
                self.keywords_edit.setText(p["route"])
            if "adv" in p:
                self.adv_edit.setPlainText(p["adv"])
            if "adv_post" in p:
                self.post_adv_edit.setPlainText(p["adv_post"])
            if "comment" in p:
                self.comment_edit.setText(p["comment"])
            if "coord_format" in p:
                self.coord_format_combo.setCurrentText(p["coord_format"])
        finally:
            self.blockSignals(False)

    def auto_detect_nproc(self):
        cpus = None
        try:
            import psutil

            cpus = psutil.cpu_count(logical=False)  # physical cores only
        except Exception:
            pass
        if cpus is None:
            cpus = os.cpu_count()  # last resort (no psutil)
        if cpus:
            self.nproc_spin.setValue(cpus)

    def auto_detect_mem(self):
        # Default fallback
        total_mb = 8000
        try:
            import psutil

            # Total system memory
            total_mb = psutil.virtual_memory().total // (1024 * 1024)
        except Exception as _e:
            logging.warning("[main_dialog.py:297] silenced: %s", _e)

        # Use roughly 75-80% of total memory to be safe, divided by nprocs
        nprocs = self.nproc_spin.value()
        rec_core = int((total_mb * 0.80) / nprocs)
        self.mem_spin.setValue(max(500, rec_core))

    def preview_file(self):
        # Legacy stub
        self.update_preview()

    def save_file(self):
        # 1. 座標データの取得 (Check for error first)
        coord_style = self.coord_format_combo.currentText()
        if "XYZ" in coord_style:
            lines = self.get_coords_lines()
        elif "gzmt" in coord_style:
            lines = self.get_zmatrix_gzmt_lines()
        else:
            lines = self.get_zmatrix_standard_lines()

        if any("Error" in line for line in lines):
            err = "\n".join(line for line in lines if "Error" in line)
            QMessageBox.critical(self, "Error", f"Coordinate Generation Failed:\n{err}")
            return

        # 2. ファイル保存ダイアログ
        default_dir = os.getcwd()
        default_base = "orca_job.inp"

        if self.filename:
            # If it's an absolute path, use its directory as default
            if os.path.isabs(self.filename):
                default_dir = os.path.dirname(self.filename)

            # Normalize and extract filename to avoid leading underscores from path separators
            norm_name = self.filename.replace("\\", "/")
            base_name = norm_name.split("/")[-1]
            if base_name:
                # Remove extension
                default_base = os.path.splitext(base_name)[0]

        # Ensure default_base doesn't have invalid chars
        import re

        default_base = re.sub(r'[\\/*?:"<>|]', "_", default_base).strip()
        # Remove any leading underscores that might have come from path separators
        default_base = default_base.lstrip("_")
        if not default_base:
            default_base = "orca_job"

        if default_base.lower().endswith(".inp"):
            default_base = default_base[:-4]

        # Apply Auto Suffix logic
        if getattr(self, "auto_suffix_cb", None) and self.auto_suffix_cb.isChecked():
            kw = self.keywords_edit.toPlainText().lower()
            adv = self.adv_edit.toPlainText().lower()
            adv_post = self.post_adv_edit.toPlainText().lower()

            suffix = ""
            if "opt" in kw:
                suffix = "-opt"
            elif "freq" in kw:
                suffix = "-freq"
            elif "nmr" in kw or "eprnmr" in adv or "eprnmr" in adv_post:
                suffix = "-nmr"
            elif "scan" in kw or "scan" in adv or "scan" in adv_post:
                suffix = "-scan"
            elif (
                "tddft" in kw
                or "cis" in kw
                or "casscf" in kw
                or "tddft" in adv
                or "cis" in adv
                or "casscf" in adv
            ):
                suffix = "-vex"

            if suffix and not default_base.endswith(suffix):
                default_base += suffix

        default_base += ".inp"

        # Combine
        default_full = os.path.join(default_dir, default_base)

        file_path, _ = QFileDialog.getSaveFileName(
            self, "Save ORCA Input", default_full, "ORCA Input (*.inp);;All Files (*)"
        )

        if file_path:
            try:
                # Use content from preview (editable)
                content = self.preview_text.toPlainText()

                with open(file_path, "w", encoding="utf-8") as f:
                    f.write(content)

                QMessageBox.information(self, "Success", f"File saved:\n{file_path}")
                # Do not close automatically
                # self.accept()
            except Exception as e:
                QMessageBox.critical(self, "Error", f"Failed to save file:\n{str(e)}")

    def insert_block_template(self):
        txt = self.block_combo.currentText()
        if "Select" in txt:
            return

        template = ""
        if "%scf" in txt:
            template = "%scf\n MaxIter 125\nend\n"
        elif "%output" in txt:
            template = "%output\n  Print[P_Basis] 2  # Required for Basis Set parsing\n  Print[P_Mos] 1    # Ensure MO coefficients are printed\nend\n"
        elif "%geom" in txt:
            template = (
                "%geom\n  Calc_Hess   true\n  Recalc_Hess 1\n  MaxIter     256\nend\n"
            )
        elif "%elprop" in txt:
            template = "%elprop\n Dipole True\n Quadrupole True\nend\n"
        elif "%plots" in txt:
            template = "%plots\n Format Gaussian_Cube\nend\n"
        elif "%tddft" in txt:
            template = (
                "%tddft\n"
                "  NRoots 10       # Number of excited states\n"
                "  MaxDim 10       # Max dimension of expansion space\n"
                "  TDA true        # Tamm-Dancoff Approximation (true/false)\n"
                "  IRoot 1         # State of interest for gradient properties\n"
                "  Triplets false  # Calculate triplet states (singlets are always on by default)\n"
                "  DoQuad true     # Compute quadrupole intensities\n"
                "end\n"
            )
        elif "%cis" in txt:
            template = "%cis\n NRoots 10\nend\n"
        elif "%mrci" in txt:
            template = "%mrci\n NewBlocks 1 1\nend\n"
        elif "%casscf" in txt:
            template = "%casscf\n Nel 2\n Norb 2\n Mult 1\nend\n"
        elif "%eprnmr" in txt:
            template = "%eprnmr\n  NUCLEI = ALL H {SHIFT, SSALL}\nend\n"
            # Switch to Post-Coordinate tab automatically
            self.adv_tabs.setCurrentWidget(self.post_adv_edit)

        current_widget = self.adv_tabs.currentWidget()
        if isinstance(current_widget, QTextEdit):
            cursor = current_widget.textCursor()
            cursor.insertText(template)

    def open_keyword_builder(self):
        self._resolve_live_mol()
        # Pass mol and main_window (self.parent()) for picking
        if (
            getattr(self, "builder_dialog", None) is not None
            and self.builder_dialog is not None
        ):
            # Sync builder with current keywords
            self.builder_dialog.parse_route(self.keywords_edit.toPlainText())
            self.builder_dialog.mol = self.mol
            self.builder_dialog.store_state()
            self.builder_dialog.show()
            self.builder_dialog.raise_()
            self.builder_dialog.activateWindow()
            return

        self.builder_dialog = OrcaKeywordBuilderDialog(
            self,
            self.keywords_edit.toPlainText(),
            mol=self.mol,
            main_window=self.parent(),
        )
        self.builder_dialog.store_state()
        self.builder_dialog.finished.connect(lambda r: self.on_builder_finished(r))
        self.builder_dialog.show()

    def on_builder_finished(self, result):
        if result == QDialog.DialogCode.Accepted:
            if getattr(self, "builder_dialog", None) is not None:
                self.keywords_edit.setPlainText(self.builder_dialog.get_route())

        self.update_preview()

    def get_coords_lines(self):
        if not self._resolve_live_mol():
            return []
        lines = []
        try:
            conf = self.mol.GetConformer()
            for i in range(self.mol.GetNumAtoms()):
                pos = conf.GetAtomPosition(i)
                atom = self.mol.GetAtomWithIdx(i)
                # Use custom symbol from XYZ Editor if present, otherwise element symbol
                symbol = (
                    atom.GetProp("custom_symbol")
                    if atom.HasProp("custom_symbol")
                    else atom.GetSymbol()
                )
                lines.append(
                    f"  {symbol: <4} {pos.x: >12.6f} {pos.y: >12.6f} {pos.z: >12.6f}"
                )
        except Exception as e:
            return [f"# Error: {e}"]
        return lines

    def _build_zmatrix_data(self):
        """Helper to build Z-Matrix connectivity and values."""
        if not self._resolve_live_mol():
            return None
        try:
            atoms = list(self.mol.GetAtoms())
            conf = self.mol.GetConformer()

            def get_dist(i, j):
                return rdMolTransforms.GetBondLength(conf, i, j)

            def get_angle(i, j, k):
                return rdMolTransforms.GetAngleDeg(conf, i, j, k)

            def get_dihedral(i, j, k, m):
                return rdMolTransforms.GetDihedralDeg(conf, i, j, k, m)

            defined = []
            z_data = []  # List of dicts for each atom

            for i, atom in enumerate(atoms):
                # Use custom symbol from XYZ Editor if present, otherwise element symbol
                symbol = (
                    atom.GetProp("custom_symbol")
                    if atom.HasProp("custom_symbol")
                    else atom.GetSymbol()
                )

                # Atom 0
                if i == 0:
                    z_data.append({"symbol": symbol, "refs": []})
                    defined.append(i)
                    continue

                # Find neighbors in defined set
                neighbors = [n.GetIdx() for n in atom.GetNeighbors()]
                candidates = [n for n in neighbors if n in defined]
                if not candidates:
                    candidates = defined[:]  # Fallback

                refs = []
                # Ref 1 (Distance)
                if candidates:
                    refs.append(candidates[-1])
                else:
                    refs.append(0)

                # Ref 2 (Angle)
                candidates_2 = [x for x in defined if x != refs[0]]
                if candidates_2:
                    refs.append(candidates_2[-1])

                # Ref 3 (Dihedral)
                candidates_3 = [x for x in defined if x not in refs]
                if candidates_3:
                    refs.append(candidates_3[-1])

                # Calculate Values
                row = {"symbol": symbol, "refs": [], "values": []}

                if len(refs) >= 1:
                    row["refs"].append(refs[0])  # 0-based index for calculation
                    row["values"].append(get_dist(i, refs[0]))

                if len(refs) >= 2:
                    row["refs"].append(refs[1])
                    row["values"].append(get_angle(i, refs[0], refs[1]))

                if len(refs) >= 3:
                    row["refs"].append(refs[2])
                    row["values"].append(get_dihedral(i, refs[0], refs[1], refs[2]))

                z_data.append(row)
                defined.append(i)

            return z_data
        except Exception as e:
            raise e

    def get_zmatrix_standard_lines(self):
        """
        Generates * int style lines.
        Format: Symbol Ref1 Ref2 Ref3 R Angle Dihed
        Refs are 1-based integers. Missing refs/values are 0/0.0.
        """
        try:
            data = self._build_zmatrix_data()
            if not data:
                return []

            lines = []
            for i, row in enumerate(data):
                symbol = row["symbol"]

                # Prepare 3 refs (1-based) and 3 values
                refs_out = [0, 0, 0]
                vals_out = [0.0, 0.0, 0.0]

                current_refs = row["refs"]
                current_vals = row.get("values", [])

                for k in range(min(3, len(current_refs))):
                    refs_out[k] = current_refs[k] + 1  # Convert to 1-based
                    vals_out[k] = current_vals[k]

                line = (
                    f"  {symbol: <3} {refs_out[0]: >3} {refs_out[1]: >3} {refs_out[2]: >3} "
                    f"{vals_out[0]: >10.6f} {vals_out[1]: >10.6f} {vals_out[2]: >10.6f}"
                )
                lines.append(line)
            return lines
        except Exception as e:
            return [f"# Error generating Standard Z-Matrix: {e}"]

    def get_zmatrix_gzmt_lines(self):
        """
        Generates * gzmt style lines (Compact).
        Format: Symbol Ref1 R Ref2 Angle Ref3 Dihed
        Refs are 1-based.
        """
        try:
            data = self._build_zmatrix_data()
            if not data:
                return []

            lines = []
            for i, row in enumerate(data):
                symbol = row["symbol"]
                line = f"  {symbol: <3}"

                current_refs = row["refs"]
                current_vals = row.get("values", [])

                # Z-Matrix logic:
                # Atom 1: Symbol
                # Atom 2: Symbol Ref1 R
                # Atom 3: Symbol Ref1 R Ref2 A
                # Atom 4: Symbol Ref1 R Ref2 A Ref3 D

                if i == 0:
                    pass
                else:
                    count = len(current_refs)
                    if count >= 1:
                        line += f"  {current_refs[0] + 1: >3} {current_vals[0]: .6f}"
                    if count >= 2:
                        line += f"  {current_refs[1] + 1: >3} {current_vals[1]: .6f}"
                    if count >= 3:
                        line += f"  {current_refs[2] + 1: >3} {current_vals[2]: .6f}"

                lines.append(line)
            return lines
        except Exception as e:
            return [f"# Error generating GZMT Z-Matrix: {e}"]

    def generate_input_content(self):
        """Generates the full content of the input file as a string."""
        content = []

        comment = self.comment_edit.text().strip()
        if comment:
            content.append(f"# {comment}")

        # 1. Resources (from UI)
        nprocs = self.nproc_spin.value()
        if nprocs > 1:
            content.append(f"%pal nprocs {nprocs} end")
        content.append(f"%maxcore {self.mem_spin.value()}")

        # 2. KeywordsLine (!)
        kw = self.keywords_edit.toPlainText().strip()
        if kw:
            if not kw.startswith("!"):
                kw = "! " + kw
            content.append(f"\n{kw}")

        # 3. Advanced Blocks (%)
        adv = self.adv_edit.toPlainText().strip()
        if adv:
            content.append(f"\n{adv}")

        # --- Coordinates ---
        is_cartesian = "Cartesian" in self.coord_format_combo.currentText()
        content.append("")  # Spacer

        charge = self.charge_spin.value()
        mult = self.mult_spin.value()

        if is_cartesian:
            content.append(f"* xyz {charge} {mult}")
            content.extend(self.get_coords_lines())
            content.append("*")
        else:
            is_gzmt = "gzmt" in self.coord_format_combo.currentText()
            if is_gzmt:
                header = "* gzmt"
                zmat_lines = self.get_zmatrix_gzmt_lines()
            else:
                header = "* int"
                zmat_lines = self.get_zmatrix_standard_lines()

            if any("Error" in line for line in zmat_lines):
                content.append(
                    "# ERROR: Z-Matrix generation failed. Falling back to XYZ."
                )
                content.append(f"* xyz {charge} {mult}")
                content.extend(self.get_coords_lines())
                content.append("*")
            else:
                content.append(f"{header} {charge} {mult}")
                content.extend(zmat_lines)
                content.append("*")

        # 4. Post-Coordinate Blocks (%) - Move here
        adv_post = self.post_adv_edit.toPlainText().strip()
        if adv_post:
            content.append("")  # Spacer
            content.append(adv_post)

        # 5. Final Consolidation (Merge blocks, dedup MaxIter etc.)
        full_text = "\n".join(content)
        return self.consolidate_orca_blocks(full_text)

    def consolidate_orca_blocks(self, text):
        """
        Merge redundant % blocks, deduplicate keywords, and ensure blank line spacing.
        Distinguishes between pre-coordinate and post-coordinate blocks.
        """
        import re

        lines = text.splitlines()

        # 1. Split into Pre-Coord, Coords, and Post-Coord zones
        coord_start = -1
        coord_end = -1
        for idx, line in enumerate(lines):
            if line.strip().startswith("*"):
                if coord_start == -1:
                    coord_start = idx
                coord_end = idx

        if coord_start != -1:
            pre_lines = lines[:coord_start]
            coord_part = lines[coord_start : coord_end + 1]
            post_lines = lines[coord_end + 1 :]
        else:
            pre_lines = lines
            coord_part = []
            post_lines = []

        def parse_zone(zone_lines):
            comments = []
            headers = []
            pal = None
            maxcore = None
            blocks = {}
            others = []
            i = 0
            while i < len(zone_lines):
                line = zone_lines[i]
                s = line.strip()
                if not s:
                    i += 1
                    continue
                if s.startswith("#"):
                    comments.append(line)
                    i += 1
                    continue
                if s.startswith("!"):
                    headers.append(line)
                    i += 1
                    continue
                if s.lower().startswith("%pal"):
                    if " end" in s.lower() or s.lower().endswith("end"):
                        pal = s
                        i += 1
                    else:
                        pal = line
                        i += 1
                        while i < len(zone_lines):
                            pal += "\n" + zone_lines[i]
                            if zone_lines[i].strip().lower() == "end":
                                i += 1
                                break
                            i += 1
                    continue
                if s.lower().startswith("%maxcore"):
                    maxcore = s
                    i += 1
                    continue
                if s.startswith("%"):
                    # One-liner
                    m_single = re.match(r"^%(\w+)\s+(.*)\s+end", s, re.I)
                    if m_single:
                        bname = m_single.group(1).lower()
                        if bname not in blocks:
                            blocks[bname] = []
                        blocks[bname].append(m_single.group(2))
                        i += 1
                        continue
                    # Multi-liner
                    m_start = re.match(r"^%(\w+)", s, re.I)
                    if m_start:
                        bname = m_start.group(1).lower()
                        if bname not in blocks:
                            blocks[bname] = []
                        i += 1
                        while i < len(zone_lines):
                            l_inner = zone_lines[i]
                            # Heuristic: only a non-indented 'end' closes a %-block
                            # This allows nested sub-blocks like Constraints...end to be captured correctly.
                            if l_inner.strip().lower() == "end" and (
                                not l_inner or not l_inner[0].isspace()
                            ):
                                i += 1
                                break
                            blocks[bname].append(l_inner)
                            i += 1
                        continue
                others.append(line)
                i += 1
            return comments, headers, pal, maxcore, blocks, others

        pre_c, pre_h, pre_pal, pre_mc, pre_b, pre_o = parse_zone(pre_lines)
        post_c, post_h, post_pal, post_mc, post_b, post_o = parse_zone(post_lines)

        # Merge blocks (Move post to pre if they share name, or keep separate?)
        # For simplicity and to satisfy "merge", we merge them.
        # But we keep track of which blocks should stay post-coord if they were ONLY there.
        final_pre_blocks = pre_b
        final_post_blocks = {}
        for bname in post_b:
            if bname in final_pre_blocks:
                final_pre_blocks[bname].extend(post_b[bname])
            else:
                final_post_blocks[bname] = post_b[bname]

        # Deduplicate keywords in merged blocks
        def dedup_block(bname, lines):
            d_keys = []
            if bname in ["scf", "geom"]:
                d_keys.append("maxiter")
            if bname in ["tddft", "cis"]:
                d_keys.append("nroots")
            if bname == "tddft":
                d_keys.extend(["maxdim", "iroot"])
            if not d_keys:
                return lines
            k_map = {}
            filtered = []
            for line in lines:
                m = re.match(r"^\s*(" + "|".join(d_keys) + r")\b\s+(.*)$", line, re.I)
                if m:
                    k_map[m.group(1).lower()] = line
                else:
                    filtered.append(line)
            return list(k_map.values()) + filtered

        for bn in final_pre_blocks:
            final_pre_blocks[bn] = dedup_block(bn, final_pre_blocks[bn])
        for bn in final_post_blocks:
            final_post_blocks[bn] = dedup_block(bn, final_post_blocks[bn])

        # Deduplicate ! keywords
        def dedup_h(h_lines):
            res = []
            for line in h_lines:
                tokens = line.split()
                unique = []
                seen = set()
                # Remove redundant Opt if more specific keyword exists
                upper_tokens = [t.upper() for t in tokens]
                has_specific_opt = any(
                    ks in upper_tokens
                    for ks in ["TIGHTOPT", "VERYTIGHTOPT", "LOOSEOPT"]
                )
                for t in tokens:
                    tu = t.upper()
                    if tu == "!":
                        unique.append(t)
                    elif tu == "OPT" and has_specific_opt:
                        continue
                    elif tu not in seen:
                        unique.append(t)
                        seen.add(tu)
                res.append(" ".join(unique))
            return res

        final_h = dedup_h(pre_h + post_h)

        # Reconstruct
        def rebuild_zone(c, h, pal, mc, blocks, others):
            pieces = []

            # Combine comments, pal and maxcore into one piece to keep them connected
            header_p = []
            if c:
                header_p.append("\n".join(c))
            if pal:
                header_p.append(pal)
            if mc:
                header_p.append(mc)
            if header_p:
                pieces.append("\n".join(header_p))

            if h:
                pieces.append("\n".join(h))
            for bname in sorted(blocks.keys()):
                inner_content = "\n".join(blocks[bname])
                pieces.append(f"%{bname}\n{inner_content}\nend")
            if others:
                pieces.append("\n".join(others))
            return pieces

        final_pre_pieces = rebuild_zone(
            pre_c,
            final_h,
            pre_pal or post_pal,
            pre_mc or post_mc,
            final_pre_blocks,
            pre_o,
        )
        final_post_pieces = rebuild_zone(
            post_c, [], None, None, final_post_blocks, post_o
        )

        all_pieces = final_pre_pieces
        if coord_part:
            all_pieces.append("\n".join(coord_part))
        all_pieces.extend(final_post_pieces)

        return "\n\n".join(all_pieces).strip() + "\n"

    # --- Preset Management ---
    def load_presets_from_file(self):
        self.presets_data = {}
        if os.path.exists(SETTINGS_FILE):
            try:
                with open(SETTINGS_FILE, "r", encoding="utf-8") as f:
                    self.presets_data = json.load(f)
            except Exception as e:
                print(f"Error loading presets: {e}")

        if "Default" not in self.presets_data:
            self.presets_data["Default"] = {
                "nproc": 4,
                "maxcore": 2000,
                "route": "! B3LYP def2-SVP RIJCOSX Def2/J Opt Freq",
                "adv": "",
                "adv_post": "",
            }

        if "Global" in self.presets_data:
            global_cfg = self.presets_data["Global"]
            if hasattr(self, "auto_suffix_cb") and "auto_suffix" in global_cfg:
                self.auto_suffix_cb.setChecked(global_cfg["auto_suffix"])

        self.update_preset_combo()

    def update_preset_combo(self):
        current = self.preset_combo.currentText()
        self.preset_combo.blockSignals(True)
        self.preset_combo.clear()

        # Add all presets except Global
        keys = [k for k in self.presets_data.keys() if k != "Global"]
        self.preset_combo.addItems(sorted(keys))
        if current in self.presets_data:
            self.preset_combo.setCurrentText(current)
        elif "Default" in self.presets_data:
            self.preset_combo.setCurrentText("Default")
        self.preset_combo.blockSignals(False)
        self.apply_selected_preset()

    def apply_selected_preset(self):
        name = self.preset_combo.currentText()
        if name not in self.presets_data:
            return
        data = self.presets_data[name]
        self.nproc_spin.setValue(data.get("nproc", 4))
        self.mem_spin.setValue(data.get("maxcore", 2000))
        self.keywords_edit.setText(
            data.get("route", "! B3LYP def2-SVP RIJCOSX Def2/J Opt Freq")
        )
        self.adv_edit.setPlainText(data.get("adv", ""))
        self.post_adv_edit.setPlainText(data.get("adv_post", ""))

        self.update_preview()

    def save_preset_dialog(self):
        name, ok = QInputDialog.getText(self, "Save Preset", "Preset Name:")
        if ok and name:
            self.presets_data[name] = {
                "nproc": self.nproc_spin.value(),
                "maxcore": self.mem_spin.value(),
                "route": self.keywords_edit.toPlainText(),
                "adv": self.adv_edit.toPlainText(),
                "adv_post": self.post_adv_edit.toPlainText(),
            }
            self.save_presets_to_file()
            self.update_preset_combo()
            self.preset_combo.setCurrentText(name)

    def delete_preset(self):
        name = self.preset_combo.currentText()
        if name == "Default":
            QMessageBox.warning(self, "Warning", "Cannot delete Default preset.")
            return
        confirm = QMessageBox.question(self, "Confirm", f"Delete preset '{name}'?")
        if confirm == QMessageBox.StandardButton.Yes:
            del self.presets_data[name]
            self.save_presets_to_file()
            self.update_preset_combo()

    def save_presets_to_file(self):
        try:
            with open(SETTINGS_FILE, "w", encoding="utf-8") as f:
                json.dump(self.presets_data, f, indent=4)
        except Exception as e:
            QMessageBox.warning(self, "Error", f"Failed to save presets: {e}")

    def save_global_settings(self):
        if not getattr(self, "ui_ready", False):
            return
        if not hasattr(self, "presets_data"):
            self.presets_data = {}
        if "Global" not in self.presets_data:
            self.presets_data["Global"] = {}
        if hasattr(self, "auto_suffix_cb"):
            self.presets_data["Global"]["auto_suffix"] = self.auto_suffix_cb.isChecked()
        self.save_presets_to_file()

    # --- Charge/Mult Logic ---
    def calc_initial_charge_mult(self):
        """Auto-detect charge/mult from molecule. Always runs as requested."""
        if not self._resolve_live_mol():
            return

        try:
            try:
                charge = Chem.GetFormalCharge(self.mol)
            except Exception:
                charge = 0
            num_radical = sum(
                atom.GetNumRadicalElectrons() for atom in self.mol.GetAtoms()
            )
            mult = num_radical + 1
            self.charge_spin.setValue(int(charge))
            self.mult_spin.setValue(int(mult))
            self.validate_charge_mult()
        except Exception as _e:
            logging.warning("[main_dialog.py:908] silenced: %s", _e)

    def validate_charge_mult(self):
        if not self._resolve_live_mol():
            return
        try:
            charge = self.charge_spin.value()
            mult = self.mult_spin.value()
            total_protons = sum(atom.GetAtomicNum() for atom in self.mol.GetAtoms())
            total_electrons = total_protons - charge
            is_valid = (total_electrons % 2 == 0 and mult % 2 != 0) or (
                total_electrons % 2 != 0 and mult % 2 == 0
            )
            if is_valid:
                self.charge_spin.setPalette(self.default_palette)
                self.mult_spin.setPalette(self.default_palette)
            else:
                p = self.charge_spin.palette()
                p.setColor(QPalette.ColorRole.Base, QColor("#FFDDDD"))
                p.setColor(QPalette.ColorRole.Text, Qt.GlobalColor.red)
                self.charge_spin.setPalette(p)
                self.mult_spin.setPalette(p)
            self.update_preview()
        except Exception as _e:
            logging.warning("[main_dialog.py:929] silenced: %s", _e)

    def closeEvent(self, event):
        if getattr(self, "builder_dialog", None) is not None and self.builder_dialog:
            self.builder_dialog.close()
        super().closeEvent(event)

    def accept(self):
        if getattr(self, "builder_dialog", None) is not None and self.builder_dialog:
            self.builder_dialog.close()
        super().accept()

    def reject(self):
        if getattr(self, "builder_dialog", None) is not None and self.builder_dialog:
            self.builder_dialog.close()
        super().reject()

    def keyPressEvent(self, event):
        if event.key() == Qt.Key.Key_Escape:
            focused = self.focusWidget()
            if isinstance(focused, (QLineEdit, QComboBox, QSpinBox, QTextEdit)):
                focused.clearFocus()
                return
        super().keyPressEvent(event)
